### ISSUE TITLE
Dotnet Fable clean -o build should is deleting files it should not delete

### ISSUE THREAD

**Issue by afaayerhan** [fable-compiler/Fable#2406] opened 2021-03-12 07:22 UTC
### Description

when you run
```bash
dotnet fable clean -o build
```
it deletes all .js files not just .fs.js
things like jest configs which are js files gets deleted 
even when they are outside the output build folder

### Repro code

create a project that has different build output folder as your code 
create unrealated .js files and run ```dotnet fable clean -o build```

### Expected and actual results

this should not delete the .js files only the .fs.js files
but it deletes everything including ones outside the build folder

### Related information

* Fable version: F# to JS compiler 3.1.2
* Operating system: MacOS big sur

**Comment by alfonsogarciacaro** [comment] 2021-03-15 03:37
Hi @afaayerhan, thanks for reporting! It seems the problem is `dotnet fable clean` didn't take the `--outDir` argument into account, so it was removing everything in the current directory (and subdirectories), this will be fixed in the next version.

About the extension, when you pass an output directory it defaults to .js instead of .fs.js. This was discussed somewhere else so it's difficult to change it now, but you can make the extension explicit with the `--extension` argument (or just `-e` in fable 3.1.8). In any case, please check the message in the confirmation as this tells you the directory and the extension of the files that will be deleted:

```fsharp
This will recursively delete all *.js[.map] files in /home/afaayerhan/my-repo/build/
Please press 'Y' or 'y' if you want to continue:
```

**Comment by afaayerhan** [comment] 2021-03-18 20:44
one other thing would be allow custom file extension even when you ```--outDir``` is provided.

**Comment by alfonsogarciacaro** [comment] 2021-03-19 05:14
Yes, the only thing that changes is the "default" file extension, when there's no `--outDir` it's ".fs.js" and when there's `--outDir` is ".js", but in either case you can pass an "explicit" file extension with the `--extension`  argument 👍

**Comment by alfonsogarciacaro** [comment] 2021-07-12 02:21
Closing for now, please reopen if there're further questions.

**Closed by alfonsogarciacaro** 2021-07-12 02:21 UTC
