### ISSUE TITLE
Lua Support for Fable

### ISSUE THREAD

**Issue by lucasteles** [fable-compiler/Fable#2753] opened 2022-01-19 13:31 UTC
### Description

[Lua](https://www.lua.org/) is a very small language largely used for configuration and games. I think that would be great to write it in F#

wdyt?

**Comment by MangelMaxime** [comment] 2022-01-19 16:04
Hello, 

there is a PR opened with a bit of work done to target Lua https://github.com/fable-compiler/Fable/pull/2509

I think they are looking for contributors to help work on it.

**Comment by alfonsogarciacaro** [comment] 2022-01-19 23:09
Thanks for the reply @MangelMaxime. Closing for now as it's a duplicate of #2509

**Closed by alfonsogarciacaro** 2022-01-19 23:09 UTC
