### ISSUE TITLE
`dotnet fable watch` stops working with `--run npx vite`

### ISSUE THREAD

**Issue by ken-okabe** [fable-compiler/Fable#3791] opened 2024-03-23 20:51 UTC
### Description

This is my first attempt at using Fable for a serious project.
Accordingly, I have followed the steps described in  **Getting Started**

https://fable.io/docs/getting-started/your-first-fable-project.html
https://fable.io/docs/getting-started/javascript.html

- **Node.js**

`dotnet fable watch`

works as expected.

- **Browser**

After setup, the command 

`dotnet fable watch --run npx vite`

 works as expected only 2-3 times when changes are made to `Program.fs` .

After that, the transpilation from `Program.fs` to `Program.fs.js` stops working, preventing Vite triggers.

`dotnet fable watch` alone without  `--run npx vite` still works fine.

### Repro code

All code is identical to **Getting Started** in the official documentation guide.

https://fable.io/docs/getting-started/your-first-fable-project.html
https://fable.io/docs/getting-started/javascript.html

### Expected and actual results

`dotnet fable watch` alone works fine forever.

`dotnet fable watch --run npx vite` works only a few times, but should work forever.

### Related information

* Fable version: `dotnet fable --version`
4.16.0

* Vite version: `npx vite --version`
vite/5.2.4 linux-x64 node-v21.7.1

* Dotnet version: `dotnet --version`
8.0.201

* Operating system
EndeavourOS (Arch Linux)

---

## Workaround

Simply do not use 

`dotnet fable watch --run npx vite`

Alternatively, execute the following commands simultaneously

`dotnet fable watch`

`npx vite`

**Comment by MangelMaxime** [comment] 2024-03-24 09:04
Hello, this is a duplicate of https://github.com/fable-compiler/Fable/issues/3365 and https://github.com/fable-compiler/Fable/issues/3631

Using `dotnet fable --verbose` will workaround the limitation.

The problem seems to be due because both Vite and Fable rewrite the console history.

**Closed by MangelMaxime** 2024-03-24 09:04 UTC

**Comment by ken-okabe** [comment] 2024-03-24 10:15
Hi, I apologize for the duplication. I searched for the issue, but couldn't find it.
Thank you for the documentation.
