### ISSUE TITLE
Compilation hangs when dotnet-sdk-7 is installed

### ISSUE THREAD

**Issue by pkese** [fable-compiler/Fable#3260] opened 2022-11-09 14:50 UTC
### Description

If I install `dotnet-sdk-7` besides `dotnet-sdk-6`, the compilation hangs after analyzing project file.

I.e. on console output, with version 6 I get full output, but on version 7 the "Started Fable compilation..." never gets printed.
```
...
Project and references (235 source files) parsed in 3443ms

Started Fable compilation...
....
```

Adding `global.json` with sdk version set to `6.0.403` fixes the problem.

### Related information

* Fable version: `3.7.20`
* Operating system:
  * Ubuntu Linux 22.04 (dotnet installed through Ubuntu's official dotnet install channel)
  * Dotnet runtimes `6.0.11` and `7.0.0`

**Comment by JaggerJo** [comment] 2022-11-09 16:06
Same on MacOS 

(.NET 7.0.100 + Fable 3.7.20)

**Comment by alfonsogarciacaro** [comment] 2022-11-09 23:11
I have seen this. I think it actually doesn't hang, just takes very long time (which is bad too). We recently changed to Buildalyzer to parse the project files, maybe updating it or changing the options helps. This issues has some info: https://github.com/daveaglick/Buildalyzer/issues/217

**Comment by marcpiechura** [comment] 2022-11-10 13:47
Hey, 

I've a similar issue after upgrading to VS 17.4, which also installs SDK 7. 
When I try to compile, I get a lot of errors like:
error FSHARP: The value, namespace, type or module 'React' is not defined
...

Adding a global.json hasn't helped initially, because I installed fable as global tool and it looks like that in this case the global.json file has no affect. After switching from a global tool to a local tool, the global.json is recognized and everything works as before. 

Regards.

**Comment by sebfia** [comment] 2022-11-10 14:57
Upgrading my local tools to use the latest fable 4 preview version solved the problem for me, if it helps anyone...

**Comment by JaggerJo** [comment] 2022-11-10 15:59
@sebfia which version exactly? Tried it yesterday without luck.

**Comment by MangelMaxime** [comment] 2022-11-11 14:13
Hello @marcpiechura ,

you error seems different compared to the others. 
Are you using beta version of any of Elmish, Feliz, Fable, Fable.React?

**Comment by marcpiechura** [comment] 2022-11-11 15:34
Hey, @MangelMaxime,

nope, stable versions for everything and I hadn’t had any issues for month, so it has to be related  to the .Net 7 update. Especially given that the global.json fix worked for me too after I switched to the local tool.

**Comment by steelcityrkp** [comment] 2022-11-12 07:27
@MangelMaxime,

I ran into the exact same issue as @marcpiechura did.  None of the 'open _namespace or module_' were actually working and nothing would compile.  This began after I updated Visual Studio (which installed the .NET 7 SDK), and it was completely resolved as soon as I created the global.json pointing at .NET 6 SDK.  [My Fable was already installed as a Local tool]

It's not apparent why, from the compiler errors why, but just the installation/existence of .NET 7 SDK on the system was the difference in my case as well.  (I also tested this on another machine that I hadn't installed the VS Update and it had worked)

**Comment by alfonsogarciacaro** [comment] 2022-11-13 02:29
Thank you everybody by your comments. This is indeed a tricky issue as it involves interaction between Fable, F# compiler, MSBuild and Dotnet SDK... and somehow seems to have fixed itself 😆 But I've also tried to improve project parsing, although I've used a heterodox approach (details in #3265). Could you please try upgrading to theta-016 and let me know if the new solution works for you? Thanks a lot for your help!

**Comment by brud** [comment] 2022-11-14 01:46
@alfonsogarciacaro hi, I have the same problem. (I tried to run `dotnet fable watch -o output -s --run npm run start` in SAFE stack client folder)

Upgrading to **theta-016** did not change anything - only the fable_modules folder is in the output folder, but not the files of my project.

**Comment by brud** [comment] 2022-11-16 16:50
@alfonsogarciacaro hi, am I doing something wrong? (at first I tried to update the tool but the error was the same)

```
dotnet tool install fable -g --prerelease
/tmp/555a7c40-b2e4-4f27-8ce3-57096e4da425/restore.csproj : error NU1301: Failed to load service index for source https://api.nuget.org/v3/index.json.
Failed to restore tool package.
Failed to install tool 'fable'. Possible reasons for failure:

* You are trying to install a pre-release and did not specify a version with the --version option.
* A package with the same name was found, but it is not a .NET tool;
* The required NuGet feed is not available, possibly due to an internet connection issue.
* Incorrect tool name entered.

See https://aka.ms/failure-installing-tool for other possible causes of failure, including forced package naming.
```

**Comment by nilekirk** [comment] 2022-11-16 16:50
Hi @alfonsogarciacaro 
We still see the problem, but with a twist: compiling twice but with a `dotnet fable clean` in between seems to be a workaround.
After the first run, files from my project are in the out put folder, but nothing I pull in via `nuget`. This is resolved in the second run.

Also, nothing from `nuget` is in `project_cracked.json` after the first run, but it's all there after the second run.

I'm attaching `--verbose` logs of the two runs (rather long file: search for START FIRST RUN and START SECOND RUN).
[fable-net7-problem.txt](https://github.com/fable-compiler/Fable/files/10023957/fable-net7-problem.txt)

**Comment by brud** [comment] 2022-11-16 18:43
@alfonsogarciacaro upgrading to **4.0.0-theta-017** seemed to solve the problem in my case (I also had to upgrade fable to a pre-release version, but that's not so important)

Thank you for your help! :)

**Comment by nilekirk** [comment] 2022-11-18 07:12
Some more clues:

This is the content of `obj` folder after `dotnet paket restore`

    VigiLyze.fsproj.net6.0.paket.resolved
    VigiLyze.fsproj.NuGet.Config
    VigiLyze.fsproj.paket.props
    VigiLyze.fsproj.paket.references.cached
    VigiLyze.fsproj.references

If I then compile the project (which fails horribly as also reported in #3267) then the content of `obj` is

    project.nuget.cache
    VigiLyze.csproj.net6.0.paket.resolved
    VigiLyze.csproj.NuGet.Config
    VigiLyze.csproj.paket.props
    VigiLyze.csproj.paket.references.cached
    VigiLyze.csproj.references
    VigiLyze.fsproj.net6.0.paket.resolved
    VigiLyze.fsproj.NuGet.Config
    VigiLyze.fsproj.nuget.dgspec.json
    VigiLyze.fsproj.nuget.g.props
    VigiLyze.fsproj.nuget.g.targets
    VigiLyze.fsproj.paket.props
    VigiLyze.fsproj.paket.references.cached
    VigiLyze.fsproj.references

The next compile (after `dotnet fable clean`) succeeds.

Now for the fun part:

I can also get a successful compilation the first time by renaming all the `*.fsproj.*` files in the `obj` folder after the first `restore` to `*.csproj.*`.

**Comment by alfonsogarciacaro** [comment] 2022-11-19 09:58
Thank you very much for the detailed information @nilekirk! I think you're on spot, the problem seems to be that we were restoring for the .fsproj but then trying to parse the .csproj. I've change the code to make sure when .csproj is used it is restored before parsing.

At least in my tests it seems to do the trick. Can you please try with 4.0.0-theta-018 and let me know if it works for you? Thanks again for all your help to debug the issue!

**Comment by pkese** [comment] 2022-11-19 18:03
`4.0.0-theta-018` works perfectly.  
It even feels faster than 3.x series.

**Comment by nilekirk** [comment] 2022-11-20 06:16
I can confirm that `4.0.0-theta-018` works perfectly for me. Thank you @alfonsogarciacaro!

**Comment by alfonsogarciacaro** [comment] 2022-11-20 06:55
Thanks a lot for confirming @pkese @nilekirk! Ok, let's close this for now and reopen if someone else is still having issues.

Yes, it should be faster now :) The reason is for C# projects Buildalyzer does a design time build. I'm not entirely sure what's happening with F# project but it seems to be something very close to a full build which can take long time for big projects.

**Closed by alfonsogarciacaro** 2022-11-20 06:55 UTC
