### ISSUE TITLE
Port not always free

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#771] opened 2017-03-25 16:37 UTC
When running an instance of Fable 1.0 beta via `dotnet fable npm-run start` the port is not always free immediately when killing the server (`Ctrl+C`).

It took up to 30-45 seconds on my computer. 
Would be nice to be able to kill the server and restart it directly after. This is useful when working on the set up :)

I am under Linux Mint 18.1 Cinnamon.

**Comment by alfonsogarciacaro** [comment] 2017-03-25 16:52
That's weird, is it a Linux thing? In Windows the port is free right after killing the process.

It's possible to stop the server by sending `[SIGTERM]` but then another script would be necessary to send the signal.

We could add the option to stop the server by pressing Enter (though another user was [complaining about this](https://github.com/fable-compiler/fable-suave-scaffold/issues/73)) or writing a command like `exit`.

**Comment by MangelMaxime** [comment] 2017-03-25 16:59
I only have linux available here so I can't be sure.

The problem isn't consistent. Sometime occurring and other time no. Perhaps this is just the Fable server taking time to close ?

**Comment by johlrich** [comment] 2017-03-25 17:43
👍 to the idea of thinking about other ways to exit that use case. My problem with the current method:

On Windows w/ PowerShell I can't seem to exit both processes no matter how many times I press `Ctrl+C`. Anything I type brings up a prompt about terminating that I can't respond to and I have to restart PowerShell to go back to normal. 

Exiting with `Ctrl+C` twice from a `cmd` window always leaves me in a workable state though and have been using that for now.

**Comment by alfonsogarciacaro** [comment] 2017-03-25 23:08
I've published a new version to try to fix the problem, could you please check? I think running `dotnet restore` is enough to get the latest version, but make sure you've `1.0.0-narumi-903` by typing `dotnet fable --version`

**Comment by alfonsogarciacaro** [comment] 2017-03-25 23:32
If you the new version is not downloading try `dotnet restore --no-cache`, if that doesn't work, you can try `dotnet clean` or removing the `obj` folder.

**Comment by johlrich** [comment] 2017-03-26 03:20
I can confirm this fixed the weird state I was getting in with Windows + PowerShell. Both shells now exit after a single `Ctrl+C`.

**Comment by MangelMaxime** [comment] 2017-03-30 21:15
I still got the same problem under linux.

**Comment by alfonsogarciacaro** [comment] 2017-03-31 00:09
@MangelMaxime What's the version you see with `dotnet fable --version`? When pressing `Ctrl+C` can you see the following messages?
```
Killing process...
Closing server...
```

**Comment by MangelMaxime** [comment] 2017-03-31 05:51
@alfonsogarciacaro I am using `1.0.0-narumi-907` and yes I am seeing this messages.

But not the way I am expected them:

```bash
Fable server started on port 61225
CWD: /home/maxime/Workspace/Hink/Showcase
npm run start

> showcase@1.0.0 start /home/maxime/Workspace/Hink/Showcase
> webpack-dev-server

Project is running at http://localhost:8080/
webpack output is served from /
Content not from webpack is served from /home/maxime/Workspace/Hink/Showcase/public
Fable loader sent: /home/maxime/Workspace/Hink/Showcase/Showcase.fsproj
F# PROJECT: /home/maxime/Workspace/Hink/Showcase/Showcase.fsproj
   /home/maxime/Workspace/Hink/Sources/Fable.Import.Pixi.fs
   /home/maxime/Workspace/Hink/Sources/Inputs/Mouse.fs
   /home/maxime/Workspace/Hink/Sources/Inputs/Keyboard.fs
   /home/maxime/Workspace/Hink/Sources/Core.fs
   /home/maxime/Workspace/Hink/Sources/Display/Label.fs
   /home/maxime/Workspace/Hink/Sources/Interactive/Button.fs
   /home/maxime/Workspace/Hink/Sources/Interactive/Checkbox.fs
   /home/maxime/Workspace/Hink/Sources/Interactive/Switch.fs
   /home/maxime/Workspace/Hink/Sources/Container/Window.fs
   /home/maxime/Workspace/Hink/Showcase/src/App.fs
Parsing F# project...
^CKilling process...

➜  Showcase git:(feature/next) Closing server...
```

As you can see the `Closing server...` is displayed on the new prompt.

**Comment by alfonsogarciacaro** [comment] 2017-03-31 08:09
Yes, that's because the server is running on a separate thread and it takes a bit to close (when you press Ctrl+C Fable sends a signal so the server terminates itself), it's the same in Windows.

But seeing `Closing server...` should mean the server has finished and the port is free. is the port 61225 still busy after that?

**Closed** 2017-03-31 20:24 UTC
