### ISSUE TITLE
Update FSharp.Core dependency to at least 4.7.2

### ISSUE THREAD

**Issue by ThisFunctionalTom** [fable-compiler/Fable#2334] opened 2020-12-23 06:05 UTC
### Description

There is an [issue](https://github.com/dotnet/fsharp/issues/6528#issuecomment-749945706) with F# compiler when compiling Fable projects referencing latest versions of Fable.Core, Feliz and/or Fable.Elmish.Debugger.

According to Phillip Carter Fable.Core should update it's FSharp.Core dependency to at least 4.7.2.
He didn't write a reason for it but I guess we could try this.
[Link to his comment](https://github.com/dotnet/fsharp/issues/6528#issuecomment-749945706)

Maybe updating the dependency can solve this issue?

**Comment by alfonsogarciacaro** [comment] 2021-01-08 15:38
Fable.Core 3.2.3 updates the FSharp.Core dependency to 4.7.2 so I'll close the issue. Though it seems this was not the cause of #2326 but this: https://github.com/dotnet/fsharp/issues/6528#issuecomment-756522991

**Closed by alfonsogarciacaro** 2021-01-08 15:38 UTC
