### ISSUE TITLE
Cannot instantiate record that implements interface

### ISSUE THREAD

**Issue by RusKnyaz** [fable-compiler/Fable#2812] opened 2022-02-07 15:56 UTC
If the record implements interface and contains field with the same name as property defined in the interface exception occurs on creation of object of record type.

Sample code:
```FSharp
type public ISome = abstract Name : string with get
    
type public MyRecord = {
        Name: string
} with interface ISome with member this.Name with get () = this.Name

try
    //try to create the record instance, it works under .NET
    let MyRecord:MyRecord = {
        Name = "asd"
    }
with Exception as e ->
            console.log(e) //<--- we a here
```

1. Compile the code above
2. Run it in browser

**Observed:** Exception like:
TypeError: Cannot set property Name of [object Object] which has only a getter
    at new MyRecord

**Expected:** No exception, the record type object created.

* Fable version: 3.7.0
* Operating system: Ubuntu 20.04

**Comment by alfonsogarciacaro** [comment] 2022-02-08 12:52
Yes, unfortunately this is "by design": record fields and interface members are attached to the type and not mangled to improve interop as mentioned [in the docs](https://fable.io/docs/communicate/fable-from-js.html#name-mangling). We tried to change this in Fable 3 but it was breaking many bindings and libraries so the behavior remained as is. However it's possible to use the `Mangle` attribute on the interface. In that case the interface members will be mangled and there won't be any collision. You can do this freely if you're sure you're not using the interface to interop with JS.

In any case, it's true we're missing compile-time checks to warn the user of attached member conflicts and how this can be solved. We need to implement that.

**Comment by RusKnyaz** [comment] 2022-02-11 16:22
Ok. Thanks. I changed the 'Name' property in the interface to the, say 'get_Name' and it solved my problem. But now I faced to another issue. I can't use interface in type matching like:
```F#
match obj with
| :? ISome some -> 
  ...    //this code path is unreachable
| _ -> 
  //we always here
  let some = obj :?> ISome // it works
  let name = some.get_Name //it works
```


Is this limitation too?

**Comment by alfonsogarciacaro** [comment] 2022-02-16 07:35
Yes, this is because we use interfaces for bindings and the objects coming from JS have no markers so we cannot easily know if the object conforms to the interface at runtime. This is one of the caveats listed in OOP with Fable: https://fable.io/docs/dotnet/compatibility.html#object-oriented-programming

**Comment by alfonsogarciacaro** [comment] 2022-06-13 07:16
If it's ok with you @RusKnyaz, let's close this are the limitations are currently by design. Please feel free to reopen or open a new issue if you have another problem or you want to start a discussion about extending Fable capabilities. Thanks!

**Closed by alfonsogarciacaro** 2022-06-13 07:16 UTC
