### ISSUE TITLE
[discussion] Fable JS performance optimization ideas

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#739] opened 2017-03-02 16:00 UTC
Currently the JavaScript version of Fable is about 10 times slower than the .NET version.
Please share any performance optimizations ideas that can potentially bridge that gap.

**Comment by Art** [comment] 2017-03-02 16:01
Fable -> TypeScript -> WebAssembly

**Comment by ncave** [comment] 2017-03-02 16:03
I've briefly looked at the Firefox and Node profilers results but I don't see any obvious bottlenecks besides a lot of GC (but maybe not enough to explain it all).

**Comment by alfonsogarciacaro** [comment] 2017-03-02 18:36
This is tricky, I need to check better but I couldn't find any performance bottleneck either. I'm also trying to avoid [performance killers](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers) in JS, so I'm not sure what else can be done to improve performance. I do have some ideas though.

Regarding the profiler:

- Apparently you cannot check the number of calls to the same function with the V8 profiler (or at least I couldn't find how), this would help focus on the parts where optimization could make more impact. Maybe we could use a Babel plugin like [this one](https://github.com/codemix/babel-plugin-trace) to trace function calls.
- There also seem to be ways to check the optimizations and deoptimizations done with the standalone V8 engine, but I haven't checked it yet. [Reference](https://www.html5rocks.com/en/tutorials/speed/v8/)

.NET features missing/different from JS:

- Is FCS using a lot of structs or floats (which in JS are heap values)?
- Maybe the structural equality checks are much more expensive in JS.
- Not exactly a different feature, but checking the profiler I noticed that some _innocent_ properties from FCS objects trigger a very deep stack when called from Fable, maybe some caching could help here.

Collections in fable-core:

- There are several functions in the `Seq` module that could be optimized, for example the different `fold` versions could use specialized loops instead of calling themselves.
- To make a faster release, I left many [functions in List and Array modules unimplemented](https://github.com/fable-compiler/Fable/blob/82f74fcd8b701f29d8749ccd8eb370d36c8e026e/src/fable/Fable.Compiler/Replacements.fs#L1292) and they've remained as such. In these cases, the corresponding function in `Seq` is called and a new List or Array is constructed afterwards. Probably it'll be more performant to have specialized functions instead. But I'm not sure of the impact.

**Comment by ncave** [comment] 2017-03-02 21:21
Nice links there, thanks @alfonsogarciacaro ! We can look at the deopt flagged functions to see if anything can be improved there: `node --trace-deopt out/testapp/project > deopt.txt`.

**Comment by alfonsogarciacaro** [comment] 2017-03-02 22:36
For reference, these are the results of running the [testapp](https://github.com/fable-compiler/Fable/tree/narumi/src/dotnet/Fable.Client.Browser/testapp) with the Sudoku sample as the test script:

.NET Core 1.0
```
InteractiveChecker created in 1905 ms
iteration 1, duration 3240 ms
iteration 2, duration 87 ms
iteration 3, duration 62 ms
iteration 4, duration 68 ms
iteration 5, duration 64 ms
iteration 6, duration 63 ms
iteration 7, duration 64 ms
iteration 8, duration 64 ms
iteration 9, duration 87 ms
iteration 10, duration 82 ms
```

node 7.0
```
InteractiveChecker created in 1853 ms
iteration 1, duration 1157 ms
iteration 2, duration 503 ms
iteration 3, duration 400 ms
iteration 4, duration 379 ms
iteration 5, duration 343 ms
iteration 6, duration 309 ms
iteration 7, duration 392 ms
iteration 8, duration 374 ms
iteration 9, duration 345 ms
iteration 10, duration 344 ms
```

Creating the InteractiveChecker takes more or less the same time in both cases (I guess most of the time is spent reading the binaries) and the first iteration **is more than twice faster in the JS version**. After that, iterations are around 5x slower in JS. Wild guess, does this mean the .NET JIT compiler is designed to make more aggressive optimizations while V8 is more concerned about the speed of the compilation itself.

I've put the result of running `node --trace-deopt out/testapp/project` [here](). Now we just need to make some sense out of all that info ;)

Also, Google is about to release [Turbofan](http://benediktmeurer.de/2017/03/01/v8-behind-the-scenes-february-edition/), let's hope it helps give another boost to the JS-compiled Fable :)

**Comment by ncave** [comment] 2017-03-02 22:50
@alfonsogarciacaro It's entirely possible that it comes down to differences in JIT, but we should still probably see if it can be nudged in the right direction.

**Comment by alfonsogarciacaro** [comment] 2017-03-02 23:29
Absolutely! In `deopt.txt` (I fixed the link above, sorry) there's a lot of `reason: prototype-check` and reason: field-check`, maybe that's worth looking at.

**Comment by alfonsogarciacaro** [comment] 2017-03-02 23:34
```html
  <p data-reason="field-type">
    This optimized code was generated in the assumption that certain properties have specific type in all instances of the given hidden class.
    It was deoptimized because this assumption was violated.
  </p>
```

This may be because the union types now use the same field for different types (depending on the case). Maybe worth to go back to the array?

**Comment by ncave** [comment] 2017-03-03 00:13
@alfonsogarciacaro Here is a nice quote from that article you linked:

> ... when JavaScript code follows a certain pattern ( avoid all kinds of performance killers, keep everything monomorphic, limit the number of hot functions ) you’ll be able to squeeze awesome performance out of V8, easily beating Java performance on similar code. But as soon as you leave this fine line of awesome performance, you often immediately fall off a steep cliff.

**Comment by Pauan** [comment] 2017-03-10 04:32
@alfonsogarciacaro It's definitely worth looking into.

I don't think the problem is because the different union types use the same field names.

It seems more likely to me that it's related to the `fable-core` functions which operate on any union type (like `equalsUnions`).

I think the best way to figure it out for sure would be to load up V8's profiling data and use [IRHydra](http://mrale.ph/irhydra/2/) which should give more information about what is being deoptimized.

**Comment by Pauan** [comment] 2017-03-10 05:10
[Here's some more profiling tips, though the articles are quite old.](https://floitsch.blogspot.com/2012/03/optimizing-for-v8-introduction.html)

**Comment by jgrund** [comment] 2017-05-08 14:57
Beyond profiling code and re-writing, I think this tool has a lot of promise:

https://prepack.io/

We should take a look at how it helps perf after it is ready for production.

**Comment by alfonsogarciacaro** [comment] 2017-05-11 20:53
Thanks for the link @jgrund! I had a look and it seems very promising, we should try to apply it to Fable REPL and see if compilation times improve :+1:

Anyways, I'm closing this to follow discussion of FCS+Fable JS package in #727.

**Closed by alfonsogarciacaro** 2017-05-11 20:53 UTC
Labels: revisit
