### ISSUE TITLE
Warnings when using strings with units of measure

### ISSUE THREAD

**Issue by kerams** [fable-compiler/Fable#1962] opened 2019-12-29 11:03 UTC
### Description

When using strings with units of measure (defined in the FSharp.UMX package), I see warnings like this:

```
WARNING in ./src/Client/Client.fs 72:48-79
"export 'string$00601$reflection' (imported as 'string$002400601$0024reflection') was not found in '../../.fable/FSharp.UMX.1.0.0/FSharp.UMX.fs'
 @ ./src/Client/Client.fsproj
 @ multi ./src/Client/Client.fsproj
```

Does this indicate a potential problem in FSharp.UMX or Fable compiler itself?

### Repro code

https://github.com/kerams/umx-repro
`fake build -t run`

### Expected and actual results

~~Expecting no warnings issued since the application seems to work fine (though I do also currently see runtime errors that could be related in a different project which uses Fable.Remoting, which in turn relies on reflection).~~

Indeed, when I remove strings with units of measure from the Fable.Remoting contract, the runtime errors disappear.

So the warnings are justified, but at the same time, I think the necessary reflection metadata should either be generated or the unit of measure erased.

### Related information

* Fable version: 2.4.11
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment] 2019-12-30 21:16
This seems to be an issue of the F# compiler. I haven't found a way to access the abbreviated type from `string<[<Measure>] 'm>` and the like (it's possible with the [measure annotated abbreviations in FSharp.Core](https://github.com/dotnet/fsharp/blob/8a9cf9885fefad80a3080d095e90ba5795d4aaaa/src/fsharp/FSharp.Core/prim-types.fs#L342-L348) though). See https://github.com/dotnet/fsharp/issues/5992

The only work around I can think of at the moment is to use a custom attribute in FSharp.UMX to indicate the abbreviated type. It would be redundant but it would give Fable access to that information. The ideal solution would be to fix it in the F# compiler, of course.

**Comment by et1975** [comment] 2020-06-09 19:48
Just hit the same issue, too bad...

**Comment by alfonsogarciacaro** [comment] 2020-06-10 03:47
Maybe we could hardcode the names of the annotated types is FSharp.UMX as in here... 🤔 https://github.com/fable-compiler/Fable/blob/7d02d3e690a9b15cb7ca823b90c20f46f13f2a37/src/Fable.Transforms/FSharp2Fable.Util.fs#L511-L515

**Comment by alfonsogarciacaro** [comment] 2020-06-11 01:53
Hmm, iirc it did work when we published the first version of FSharp.UMX but we may have broken it 😠 I should have added it to the tests.

Let's hope that https://github.com/dotnet/fsharp/pull/6805 gets merged soon and we can access the SRTP witness from Fable.

**Comment by kerams** [comment] 2020-06-13 18:17
I reckon if this workaround is trivial to implement, it would be better than nothing for the time being.

**Comment by alfonsogarciacaro** [comment] 2020-11-01 22:39
This seems to work in this branch #2240

**Closed** 2020-11-01 22:47 UTC
Labels: witnesses

**Comment by et1975** [comment] 2020-11-20 17:32
Does the fix require Fable 3.x then?

**Comment by alfonsogarciacaro** [comment] 2020-11-20 23:29
Yes, but you'll get many other benefits from the upgrade too :)

**Comment by et1975** [comment] 2020-11-22 18:56
Getting a Fable compilation error when using UOM Guid:
> error EXCEPTION: Cannot find dll entity System.Guid

**Comment by et1975** [comment] 2020-11-23 15:40
I thought I'd reproduce the problem in the PR, but the tests compile, so now I don't know what to think. I get the error in all the files where I use the Guid UOM types, but not in the file that defines the types.

**Comment by alfonsogarciacaro** [comment] 2020-11-23 23:04
I think I found the issue, I will add a fix for next release.

**Comment by et1975** [comment] 2020-11-24 15:18
I think I found it as well - fable3 doesn't seem to be defining `FABLE_COMPILER` (anymore?), once defined it started compiling.

**Comment by alfonsogarciacaro** [comment] 2020-11-25 19:15
@et1975 Can you please try with latest release? `dotnet tool update fable --version "3.0.0-*"`

**Comment by et1975** [comment] 2020-11-25 20:17
Woo-hoo, you rock, as usual 👍 
Thank you!
