### ISSUE TITLE
Problem with sprintf in React component

### ISSUE THREAD

**Issue by ghost** [fable-compiler/Fable#1433] opened 2018-06-18 17:00 UTC
### Description

I encountered a problem with `sprintf` when I tried to use it with a React component ([InputNumber of Ant Design](https://ant.design/components/input-number/))
When I use regular string concatenation everything works as expected.

### Repro code

![bug_sprintf](https://user-images.githubusercontent.com/3251459/41550560-709455d8-7329-11e8-9ffc-77dfb5a686d8.gif)

#### Expected
No exception :)

#### Actual
![capture](https://user-images.githubusercontent.com/3251459/41549645-d09d1788-7326-11e8-9051-9b34a22b67d2.PNG)

### Related information
* `dotnet fable --version` = 1.3.15
* `dotnet --version` = 2.1.105
* Windows 10 Education Version 10.0.17134 Build 17134
* Chrome Version  67.0.3396.87 (Official Build) (64-bit)

**Comment by kfrie** [comment] 2018-06-29 10:54
Hi @alfonsogarciacaro 

sorry for the late reply. I'd like to use this as an opportunity to contribute to Fable. I just need to onboard compiler development, then I hopefully manage to send a PR with a fix 😄.

**Comment by alfonsogarciacaro** [comment] 2018-06-29 11:07
That'd be great, please note that development is happening now in `dev2.0` branch, so it's better if you send the PR to that branch. Please let me know if you need any help :+1:

**Comment by kfrie** [comment] 2018-06-29 11:39
good to know, I just created a feature branch on `master` since I thought you might want to merge the PR in as a hotfix for Fable 1.x.

Thank you for being so helpful, I will get back in touch if I need some 😄

**Comment by kfrie** [comment] 2018-06-29 17:04
I skimmed a bit through the tests and code and I think might be the right places to start: 

https://github.com/fable-compiler/Fable/blob/60173b6d1dd6199dc6e9b317a544e2b028382446/src/js/fable-core/String.ts#L128-L156

I would then add a test in this file

https://github.com/fable-compiler/Fable/blob/60173b6d1dd6199dc6e9b317a544e2b028382446/tests/Main/StringTests.fs#L45-L87

How to I run the tests and what is your usual development workflow for features/fixes ?

**Comment by alfonsogarciacaro** [comment] 2018-07-02 20:56
I actually prefer not to touch `master` because `dev2.0` has diverged a lot and at some point I'll have to manually go through the commit list and 

You can run the `All` build target. But for faster development, I usually use the [QuickTest file](https://github.com/fable-compiler/Fable/blob/101309d008fb8ea8283634366305d2566d127d0f/src/tools/QuickTest.fs). There're some FAKE targets to run the quicktest, but recently I'm using a shell script (I'm on macOS but I think you can run it on Windows too with Git Bash) so after cloning, check out `dev2.0`, paste your tests at the bottom of the QuickTest file and then on a terminal just type:

```shell
cd src/tools
sh quicktest.sh --build-core
```

`--build-core` is only needed the first time (or whenever the src/js/fable-core files change). After that, if you only edit the JS/TypeScript files, you can use the argument `--build-js-core` instead which is much faster.

**Comment by alfonsogarciacaro** [comment] 2018-12-12 10:02
Hi @kfrie! What's the status of this? I tried to reproduce it but it seems to work in latest Fable, can you please check?

**Comment by alfonsogarciacaro** [comment] 2021-05-11 16:51
Closing for now, please reopen if this is still an issue with Fable 3.

**Closed by alfonsogarciacaro** 2021-05-11 16:51 UTC
Labels: waiting-feedback
