### ISSUE TITLE
Babel: "You must pass a scope and parentPath unless traversing a Program/File."

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#700] opened 2017-02-06 06:31 UTC
This is happening in narumi (but not in master, master works), was there any related change? (see #483, although it may be a bit different as that one is passing).

```
Error: C:/Projects/FSharp.Compiler.Service_fable/src/fsharp/fcs-fable/out/fsharp/TastPickle.js:
You must pass a scope and parentPath unless traversing a Program/File. Instead of that you
tried to traverse a "Identifier" node without passing scope and parentPath.
    at traverse (C:\Projects\Fable\build\fable\node_modules\babel-traverse\lib\index.js:73:13)
    at File.buildCodeFrameError (C:\Projects\Fable\build\fable\node_modules\babel-core\lib\transformation\file\index.js:436:35)
    at Scope.checkBlockScopedCollisions (C:\Projects\Fable\build\fable\node_modules\babel-traverse\lib\scope\index.js:402:27)
    at Scope.registerBinding (C:\Projects\Fable\build\fable\node_modules\babel-traverse\lib\scope\index.js:596:16)
    at Scope.registerDeclaration (C:\Projects\Fable\build\fable\node_modules\babel-traverse\lib\scope\index.js:500:14)
    at Object.BlockScoped (C:\Projects\Fable\build\fable\node_modules\babel-traverse\lib\scope\index.js:244:28)
    at Object.newFn (C:\Projects\Fable\build\fable\node_modules\babel-traverse\lib\visitors.js:318:17)
    at NodePath._call (C:\Projects\Fable\build\fable\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Projects\Fable\build\fable\node_modules\babel-traverse\lib\path\context.js:44:14)
    at NodePath.visit (C:\Projects\Fable\build\fable\node_modules\babel-traverse\lib\path\context.js:105:12)
```

**Comment by alfonsogarciacaro** [comment] 2017-02-06 09:27
Damn! This is an error that's usually difficult to track down. From the other times I've seen it, it's usually caused because the same variable is declared twice in the same JS scope or the variable is used outside its scope. It's unfortunate that the Babel error message doesn't give you some more info (like the name of the Identifier) that allows the location of the error.

I think at the moment the biggest difference in code generation between narumi and master is the new runtime representation of DUs (that shouldn't affect scopes) and the (soon to become controversial) flattening lambdas feature (see [this commit](https://github.com/fable-compiler/Fable/commit/4358d1617038ea5df9074e4b605e1c749b218da3) which basically rescues this [PR](https://github.com/fable-compiler/Fable/pull/335)).

Flattening lambdas shouldn't break scopes, but sometimes when combing pipes and partial applications the F# compiler may create extra variables that get out of scope when [the lambdas are being wrapped to correct arity](https://github.com/fable-compiler/Fable/blob/35b1c0b41cf45da8665bb81fbbfcf437eb4eeedc/src/dotnet/Fable.Core/AST/AST.Fable.Util.fs#L406).

If you cannot find more info about the problem I'll try to compile FCS and use the debugger to get to the point when the exception is thrown and inspect the AST to try to find the corresponding F# code.

**Comment by ncave** [comment] 2017-02-06 16:59
Here is the babel ast if that helps:

[TastPickle.zip](https://github.com/fable-compiler/Fable/files/755297/TastPickle.zip)

**Comment by alfonsogarciacaro** [comment] 2017-02-06 23:52
Unfortunately, I haven't developed yet the skills to make sense out of an AST of those dimensions (the formatted JSON of the Babel AST is over 100_000 LOC) 😉 I tried to compile your FCS fork with Fable's narumi branch but I got errors, how are you building it?

**Comment by ncave** [comment] 2017-02-07 08:36
Yes, that's the error during compilation (see OP above).

**Comment by alfonsogarciacaro** [comment] 2017-02-07 09:21
Sorry, I meant what are the steps you're doing now to build FCS with Fable. I tried the `fable` branch in your FCS fork, first built the `Build.Netcore` target and then when running fable (using `narumi`) I got the following error before getting to the point where I can see the output you posted above:

```Cannot find replacement for System.Resources.ResourceManager..ctor in FSComp.fs, L32```

**Comment by ncave** [comment] 2017-02-07 09:50
@alfonsogarciacaro There is a codegen step before you compile, as listed in the notes to the FCS PR.

Steps:
```
cd /Projects/FSharp.Compiler.Service_fable
build CodeGen.NetCore -d:FABLE_COMPILER
cd /Projects/FSharp.Compiler.Service_fable/src/fsharp/fcs-fable
node /Projects/Fable_narumi/build/fable
```

**Comment by ncave** [comment] 2017-02-07 11:19
@alfonsogarciacaro I've narrowed it down to [this](https://github.com/ncave/FSharp.Compiler.Service/blob/fable/src/fsharp/TastPickle.fs#L1569-L1581), if commented the error goes away.

**Comment by alfonsogarciacaro** [comment] 2017-02-07 11:26
Ah, crap! Now I remember, I did remove the brackets for the switch cases (which were causing #483) because I thought I already fixed that problem by giving unique identifiers to all variables in the same method. The test I had for #483 is passing but apparently it didn't fix all situations, I'll try to check if I can find the cause or I'll put back the case brackets.

And thanks for the build instructions! Somehow I forgot about the proper code generation step 😅

**Comment by alfonsogarciacaro** [comment] 2017-02-07 22:04
Hopefully this should be solved in latest `narumi`. At the end it was not specifically the switch case brackets but the fact that the code was not in a method but in the module level, so Fable wasn't creating a scope of unique var names for it.

Maybe we should add FCS compilation to the build in the CI servers. What do you think?

**Closed by alfonsogarciacaro** 2017-02-07 22:04 UTC

**Comment by ncave** [comment] 2017-02-07 22:51
@alfonsogarciacaro Sure, if you want to, as another (large) test case, but you'll have to pull FCS as a paket dependency.

**Comment by 0x53A** [comment] 2018-10-24 14:04
This is one of the few google results for

``You must pass a scope and parentPath unless traversing a Program/File. Instead of that you tried to traverse a Identifier node without passing scope and parentPath.``

So I would like to spam my issue and solution:

After upgrading from Fable 1.x to 2.x I got this error in previously compiling code.

As mentioned above, the error was a duplicated identifier.

I had code similar to this:

```f#
type private SomeReactComponent(props) =
    // ..

let SomeReactComponentp = ofType<SomeReactComponent, _, _> p []
```

After renaming the type, compilation works.

**Comment by alfonsogarciacaro** [comment] 2018-10-29 10:28
Thanks @0x53A! Yes, I didn't know this combination was possible in F# so I haven't added a check/mangling for this, hopefully I can do it for the next release. Related #1607
