### ISSUE TITLE
The generated Python code module name is converted to lowercase

### ISSUE THREAD

**Issue by hlizard** [fable-compiler/Fable#3079] opened 2022-08-16 03:29 UTC
### Description

The generated Python code module name is converted to lowercase. The module name should be capitalized like "Chapter_14" generated by `4.0.0-snake-island-alpha-012`

### Repro code

`4.0.0-snake-island-alpha-020` result:
```python3
from __future__ import annotations
from fable_modules.fable_library.types import to_string
from chapter_14.模块测试 import (车辆__ctor_7B00E9A0, 车辆, 车辆__跑_5E38073B)

a: 车辆 = 车辆__ctor_7B00E9A0(50, 1)

print(to_string(a))

车辆__跑_5E38073B(a, 5)


```

### Expected and actual results

`4.0.0-snake-island-alpha-012` result:
```python3
from __future__ import annotations
from fable_modules.fable_library.types import to_string
from Chapter_14.模块测试 import (_8F66_8F86__ctor_7B00E9A0, _8F66_8F86, _8F66_8F86___8DD1_5E38073B)

a : _8F66_8F86 = _8F66_8F86__ctor_7B00E9A0(50, 1)

print(to_string(a))

_8F66_8F86___8DD1_5E38073B(a, 5)


```

### Related information

* Fable version: `4.0.0-snake-island-alpha-020`
* Operating system: win10

**Comment by alfonsogarciacaro** [comment] 2022-08-16 04:14
@dbrattli can confirm but I think this is to conform to Python conventions. We could have a CLI option to change the default behaviour but not sure it it's worth it. Is there any strong reason you prefer to keep the module names capitalized @hlizard?

**Comment by hlizard** [comment] 2022-08-16 04:59
> @dbrattli can confirm but I think this is to conform to Python conventions. We could have a CLI option to change the default behaviour but not sure it it's worth it. Is there any strong reason you prefer to keep the module names capitalized @hlizard?

This is just a small test project for me. When I created it, I didn't care whether the module name should be uppercase or lowercase. The version used at that time was `4.0.0-snake-island-alpha-012`. Now after upgrading to `4.0.0-snake-island-alpha-020`, I find that it cannot be executed correctly as before:
```
ModuleNotFoundError: No module named 'chapter_14'
```

However, I think the Convention is just a suggestion. People should be allowed to choose to use different specifications in a particular project.

**Comment by dbrattli** [comment] 2022-08-16 06:08
Yes, it's a suggestion. Everything in PEP-8 is optional, but we still want to generate code that confirms to PEP-8. What did the original code look like?

**Comment by hlizard** [comment] 2022-08-16 06:34
> Yes, it's a suggestion. Everything in PEP-8 is optional, but we still want to generate code that confirms to PEP-8. What did the original code look like?

`Chapter_14\test.fs`:
```fsharp
module test
open System

let a=模块测试.车辆(50, 1)
Console.WriteLine(a.ToString())
a.跑 5
```
[fable4test.zip](https://github.com/fable-compiler/Fable/files/9348383/fable4test.zip)

compile and run:
```
dotnet fable Chapter_14.fsproj --lang python
python3 -mChapter_14.test
```

**Comment by dbrattli** [comment] 2022-08-16 06:42
Ok, thanks. I will see if I can change this back again for project modules outside of fable modules.

**Comment by dbrattli** [comment] 2022-08-21 06:07
Closing since this should be fixed in -alpha-21

**Closed by dbrattli** 2022-08-21 06:07 UTC
