### ISSUE TITLE
Consider several NuGet packaging enhancements

### ISSUE THREAD

**Issue by cartermp** [fable-compiler/Fable#2439] opened 2021-05-09 14:09 UTC
Hey fine fable folks 👋 

There are a few modifications to packaging for NuGet that you may want to consider:

* Adding an icon to packages
* Adding a license expression
* Publishing symbols

Additionally, it's considered a best practice to have an organization be the owner and publisher of a package or packages when it maps to an organization on GitHub. Individuals with publishing rights would be members of the organization, so it wouldn't materially impact their ability to publish things.

An example of all of the above is the [XPlot.Plotly](https://www.nuget.org/packages/XPlot.Plotly/) package.

Happy to send some PRs for the first three items if you're interested. Any org-level stuff would have to be taken care of by someone with permissions, though.

**Comment by MangelMaxime** [comment] 2021-05-09 19:03
Hello @cartermp,

I agree with you.

It shouldn't be too hard to add the different information to the different project using a `Directory.Build.props` we could kind of copy it in the different repository.

> Publishing symbols

I am kind of waiting for 5.0.300 to be released as there is a new NuGet `DotNet.ReproducibleBuilds` which seems to configure it for us (source link). Unless you are speaking about something else?

**Comment by MangelMaxime** [comment] 2021-05-09 19:14
Also, @nojaf started doing that on 2 projects if you want to review one of the PR

https://github.com/fable-compiler/fable-browser/pull/62 

Like that we can take inspiration from it for others repositories :)

How does managing the organization works ? Can several people be admin so if someone his not available anymore someone else can add members etc.?

**Comment by alfonsogarciacaro** [comment] 2021-05-10 02:49
Hi @cartermp! Thank you and @MangelMaxime for the ideas. Yes, it'd be good to improve the publishing of the Nuget packages, so far I've been quite sloppy with this. (Every time I see the licence warning I want to fix but then I follow the provided link and cannot find the solution I give immediately up 😅). There are also some ideas [here](https://github.com/fable-compiler/fable-compiler.github.io/issues/86#issuecomment-823200266) to improve the search results for the packages. Basically adding tags and a readme, I think.

It'd be great a to get a PR with the proposals that we can use as a base for other packages. And having just a single file like `Directory.Build.props` as @MangelMaxime says that we can just copy/paste to other repos would be ideal. If some automation is required, this is the function that I usually use for publishing: https://github.com/fable-compiler/Fable/blob/caa715f1156be29c8dd9b866a03031a1852b3186/src/fable-publish-utils/PublishUtils.fs#L547

**Comment by alfonsogarciacaro** [comment] 2021-05-10 03:07
I've created a Fable organization in nuget and sent and invitation for Maxime to join as admin. https://www.nuget.org/profiles/Fable

I had to use my personal e-mail address because I don't have a specific one for Fable and it seems you cannot link it to a github org, only use Gravatar images so it's using a default profile picture :/ I assume that in order to publish under the organization name I just need to generate a new API key for the organization.

![image](https://user-images.githubusercontent.com/8275461/117601063-45d22280-b188-11eb-92f5-6706bc45531b.png)

**Comment by alfonsogarciacaro** [comment] 2021-05-11 01:55
Adding @nojaf to the discussion as he has sent a couple of PRs to fix the issue with the licence. Maybe we can agree on a "standard" PR to fix the licence plus the other two points mentioned on top and the tags, that we can use for most of Fable-related repos?

**Comment by cartermp** [comment] 2021-05-12 01:07
Done in https://github.com/fable-compiler/Fable/pull/2441

This should get fable packages in mostly good shape. They won't be built with determinism on yet, but that isn't an issue here. I believe there are some targets in the .NET SDK that activate only for C# that the F# team (yay, us!) has to move so that we can also benefit from it.

**Closed** 2021-05-14 04:05 UTC
