### ISSUE TITLE
Nuget packages are not compiled on .NET 7 rc 1

### ISSUE THREAD

**Issue by kerams** [fable-compiler/Fable#3182] opened 2022-09-18 05:56 UTC
### Description

Everything works fine when compiling a Fable project with .NET 7 Preview 7, but installing the release candidate causes some of the dependent files (from Nuget packages) not to be compiled.

### Repro code

- Install .NET 7 Preview 7
- Clone https://github.com/kerams/7-repro
- dotnet tool restore
- dotnet fable .\Lib.fsproj
  - Compiles successfully
  - Project and references (**2 source files**) parsed in 1615ms
- Install .NET 7 rc 1
- dotnet fable clean
- dotnet fable .\Lib.fsproj
  - Compilation fails with
  ```
  .\Library.fs(3,6): (3,11) error FSHARP: The namespace or module 'Fable' is not defined. (code 39)
  .\Library.fs(5,13): (5,17) error FSHARP: The value, namespace, type or module 'Diff' is not defined. (code 39)
  ```
  - Project and references (**1 source files**) parsed in 1610ms
  - Only `fable-library.3.7.18` is visible in fable_modules

### Related information

* Fable version: 3.7.18
* Win 10

**Comment by kerams** [comment] 2022-10-09 13:59
Anyone else see this or just me? It could be serious what with the .NET 7 release next month, when more and more people start upgrading.

**Comment by alfonsogarciacaro** [comment] 2022-10-09 16:25
Sorry @kerams, when I first saw this issue I read the title too quickly and I thought it was about compiling this repo with .NET 7. I've tried now and I can reproduce. It looks the result when parsing the .fsproj doesn't include the references to the packages' binaries. It may be related with Dotnet.ProjInfo, I think it was parsing the output of MsBuild and this may have changed with .NET 7.

Unfortunately, I'm not sure if we'll have time to fix this before Fable 4 release. Let's see what happens with the .NET 7 release. If the problem persists, we can check if #3097 helps. In the worst case we can just say Fable is not compatible with .NET 7 yet. AFAIK there are no new F# or BCL features Fable benefits from. I understand this will be annoying for shared projects that want to update the backend part quickly, although in that case you can still use a separate `global.json` to lock the dotnet sdk version for FAble.

**Comment by MangelMaxime** [comment] 2022-10-10 08:37
@alfonsogarciacaro 

Ionide needed to make improvements/fixes in Ionide.ProjInfo in order to have .NET 7 preview works. So, I think upgrading to Ionide.ProjInfo will become mandatory.

https://github.com/ionide/ionide-vscode-fsharp/issues/1758

**Comment by nneeoo** [comment] 2022-10-10 08:47
@alfonsogarciacaro
I have both runtimes installed, .net 7 RC 1 and .net 6. Sheer presence of .net 7 SDK brakes fable.
You have to just install .net 7 SDK to brake fable.

It would be very inconvenient to have either fable or .net 7 SDK.

**Comment by kerams** [comment] 2022-10-10 08:54
@nneeoo, Alfonso's workaround did the trick for me.

Add global.json for .NET v6 into your Fable project and make sure any projects compiled by Fable don't target net6.0. I do get some warnings with this setup about FSharp.Core resolution problems, but everything appears to work, so I am content with it for the time being.

**Comment by nneeoo** [comment] 2022-10-10 09:12
@kerams, worked for me too, thanks.

**Comment by alfonsogarciacaro** [comment] 2022-10-10 14:27
I've tested with #3097 but unfortunately it doesn't seem to be compatible with dotnet sdk 7, only 6.0.400 :/ I've checked latest Ionide and it seems to include binaries for both net6.0 and net7.0. Does this mean we need to do the same in order to parse projects with both SDKs? Maybe @baronfel can help here?

**Comment by baronfel** [comment] 2022-10-10 14:36
So the core problem you need to be able to solve is executing the `fable` tool on a .net 7 runtime. This allows the MSBuild bindings to attach to the MSBuild from the .NET SDK. There are a few ways to do this:

* rollforward
* explicitly setting the runtime to use via `dotnet --fx-version <X> <path/to.dll>`
* multitargeting the tool

of these, the least hassle to me was multitargeting the tool. I would recommend that approach going forward as well to other tools that need to work across SDK versions.  This is very similar to the problems we had in FSAC/Proj-Info during the 5-to-6 transition, and it ends up being easier and more predictable all around to just multitarget.

**Comment by alfonsogarciacaro** [comment] 2022-10-10 15:10
Thanks a lot for the quick reply @baronfel. I tried building Fable for net7.0 target but I get this error now, any ideas?

```
alfon@LAPTOP-V7RGQGT0 MSYS ~/repos/7-repro (master)
$ dotnet ../Fable/src/Fable.Cli/bin/Debug/net7.0/fable.dll --verbose
Fable: F# to JavaScript compiler 4.0.0-theta-011 (status: beta)
Thanks to the contributor! @jmmk
Stand with Ukraine! https://standwithukraine.com.ua/

Parsing Lib.fsproj...
.> cmd /C dotnet restore Lib.fsproj -p:FABLE_COMPILER=true -p:FABLE_COMPILER_4=true -p:FABLE_COMPILER_JAVASCRIPT=true
  Determining projects to restore...
  All projects are up-to-date for restore.
Loading project 'C:/Users/alfon/repos/7-repro/Lib.fsproj'.
Failed to load project 'C:\Users\alfon\repos\7-repro\Lib.fsproj' because 'Could not load type 'Microsoft.Build.Framework.Telemetry.BuildTelemetry' from assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.'
```

**Comment by baronfel** [comment] 2022-10-10 15:15
Can you point me to the code in this repo that has the PackageReferences to Ionide.ProjInfo and the Microsoft.Build packages? All  of the MSBuild packages should be marked as `PrivateAssets="all"` and `ExcludeAssets="runtime"`. Otherwise you'll bundle MSBuild into your application instead of lazy-loading it from the SDK.

**Comment by alfonsogarciacaro** [comment] 2022-10-10 15:40
That did the trick (partially) @baronfel! Now the tool is working. The bad news is that we're back to square one because when parsing the project the .dll references from the nuget packages are not returned so Fable cannot locate the sources (which is the problem mentioned in the first comment).

I'm testing with [Ionide-ProjInfo-test branch](https://github.com/fable-compiler/Fable/blob/10ef120298b9ab04e35204d453b229f9152a0406/src/Fable.Cli/Fable.Cli.fsproj) which is based on PR #3097 and the test project provided by @kerams (see first comment). I do the following:

```
cd src/Fable.Cli
dotnet build -c Release
cd ../../../7-repro
dotnet ../Fable/src/Fable.Cli/bin/Release/net7.0/fable.dll --verbose
```

And these are the logs:

```
Fable: F# to JavaScript compiler 4.0.0-theta-011 (status: beta)
Thanks to the contributor! @i-p
Stand with Ukraine! https://standwithukraine.com.ua/

Parsing Lib.fsproj...
.> cmd /C dotnet restore Lib.fsproj -p:FABLE_COMPILER=true -p:FABLE_COMPILER_4=true -p:FABLE_COMPILER_JAVASCRIPT=true
  Determining projects to restore...
  All projects are up-to-date for restore.
Loading project 'C:/Users/alfon/repos/7-repro/Lib.fsproj'.
Successfully loaded project 'C:\Users\alfon\repos\7-repro\Lib.fsproj'.
loadedProjects [|"C:\Users\alfon\repos\7-repro\Lib.fsproj"|]
fable-library: C:\Users\alfon\repos\Fable\build/fable-library
Project and references (1 source files) parsed in 2136ms

F# PROJECT: Lib.fsproj
    --define:TRACE
    --define:RELEASE
    --define:NET
    --define:NET7_0
    --define:NETCOREAPP
    --define:NET5_0_OR_GREATER
    --define:NET6_0_OR_GREATER
    --define:NET7_0_OR_GREATER
    --define:NETCOREAPP1_0_OR_GREATER
    --define:NETCOREAPP1_1_OR_GREATER
    --define:NETCOREAPP2_0_OR_GREATER
    --define:NETCOREAPP2_1_OR_GREATER
    --define:NETCOREAPP2_2_OR_GREATER
    --define:NETCOREAPP3_0_OR_GREATER
    --define:NETCOREAPP3_1_OR_GREATER
    --nowarn:IL2121
    --noframework
    --nologo
    --simpleresolution
    --nocopyfsharpcore
    --nowin32manifest
    --warn:3
    --fullpaths
    --flaterrors
    --optimize-
    --define:FABLE_COMPILER
    --define:FABLE_COMPILER_4
    --define:FABLE_COMPILER_JAVASCRIPT
    --optimize-
    C:/Users/alfon/repos/7-repro/Library.fs

Started Fable compilation...
Type checked: Library.fs
Type check finished
Compiled 1/1: Library.fs

Fable compilation finished in 1153ms

.\Library.fs(3,6): (3,11) error FSHARP: The namespace or module 'Fable' is not defined. (code 39)
.\Library.fs(5,13): (5,17) error FSHARP: The value, namespace, type or module 'Diff' is not defined. (code 39)
Compilation failed
```

**Comment by baronfel** [comment] 2022-10-10 15:42
Ok, that's good actually. I think you're now hitting https://github.com/ionide/proj-info/issues/171, which is also hitting FSAC, Ionide, F#.Formatting, etc.  Hooray for shared failure :)

I think at this point you've done the infrastructure side of things and now just have to wait for that issue to be resolved.

**Comment by alfonsogarciacaro** [comment] 2022-10-11 10:48
Thank you @baronfel! Unfortunately, this means Ionide.ProjInfo doesn't help here because this is the same issue we had with Dotnet.ProjInfo. Using Buildalyzer instead seems to work (see #3229) and avoids the need to distribute different versions of Fable for each SDK (not sure how this can be done).

**Closed** 2022-10-12 07:08 UTC
