### ISSUE TITLE
Fable >= 3.7.3 typeof<'a>.Name is always "String"

### ISSUE THREAD

**Issue by zelenij** [fable-compiler/Fable#2841] opened 2022-03-12 03:59 UTC
### Description

For Fable >= 3.7.3 typeof<'a>.Name is always "String", regardless of the type 'a.  It works fine with 3.7.0 and many versions from 3.6.2 below.

The online runner at fable.io uses Fable 3.7.0-beta, which doesn't seem to have the same problem.

### Repro code

```
let inline getName<'a>() = typeof<'a>.Name

type Something = {
    Id: int
    Value: string
}

alert(getName<Something>())
```

### Expected and actual results

Expected: Something
Actual: String

### Related information

* Fable version: `dotnet fable --version` 3.7.5
* Operating system - MacOS
* .NET6

**Comment by alfonsogarciacaro** [comment] 2022-03-16 04:28
Sorry for the late reply @zelenij, I've tried your code with Fable 3.7.5 but I couldn't reproduce the issue, it correctly shows "Something" for me. Where do you see this problem?

**Comment by zelenij** [comment] 2022-03-23 06:13
Interesting, just tried to reproduce with 3.7.7 and no problem... might have been fixed in between :)

**Comment by alfonsogarciacaro** [comment] 2022-03-23 07:40
Yes, there's been several changes with Fable internals that may have caused some regressions, but happy to hear is fixed for you with latest version. Let's close the issue for now but please reopen if you notice anything else. Thanks!

**Closed by alfonsogarciacaro** 2022-03-23 07:40 UTC
