### ISSUE TITLE
Function decorated with `[<NamedParams>]` fails at runtime if all the arguments are optional and none are provided

### ISSUE THREAD

**Issue by Freymaurer** [fable-compiler/Fable#3480] opened 2023-06-27 13:02 UTC
### Description

Hey i am working on a library we want to offer for js as well as f#. So to improve JS syntax we wanted to use `[<NamedParams>]` on members.
I got a very strange error of:
![image](https://github.com/fable-compiler/Fable/assets/39732517/976e4088-1b73-4783-87c8-a76aca69f0be)

.. when running my Fable.Mocha tests. To add to this:

- If i use `[<NamedParams(fromIndex=0)>]` or `[<NamedParams>]` it runs for Example 1.
- Example 2 raises a similiar error no matter if i use `(fromIndex)` or not. So i would suspect the issue being `?param` f# syntax
- Fable Repl replicating Example 2 runs.

### Repro code

**Fable Repl**

[link](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwFgBQBA2gDwCCALhXAMYAWAsmALYJhYDOAfALoEUBPcFDJYaZDhzgCoAXigECUZVADeSlZoD0OqACkAygHkAcgFoAMgBEoASwAmkCrYBmt9qihGISGThQAbnAQFFAu2FAAVhzA0LbAqBqaygCSNgBcUBwUWLYQAOZQoM6xSck6WlAMAK7ZUGxQ1RC2AI7VYHbQsR3Z1fYCZZowtigmcMwdmdm5BUUgJRCDKkxwHNU4EyEAKkKTWTl5hcXxi-jJKltg9BDASMD5AjvCUwezx6Vn51CX17f3AgAFJBwCjhLDMKAvGZHeYnJbKLaIFAcSFQABKYA4tgAXmBRFhpCRpocuPCoAD2GCJpxUcTZkhbHV3qcvlBMMxNhQUVDDlAGUzYR9NABfJJlbIg2w0KATVjsGVwADWHTJAAoHLTXjCFgBKNUuUbjPZ07UnPWfc6qiardYsJxPY1aua6tUUK50G53B4OzXQ51m13uz3-IEgqm+3nM82s1XUZCY1EYrG4-GEk1caNfVXgLBU9jc-Z+-mhKNqmjADlOAsmvmMkuCiA6uQKC3JdSt1lpZsOMlDEZgMYTZsGgdG3vLMA2jb23bN61rafbXbjhFBv7e2fyN2-L2PZcdr4-D3rwHA0HYCFbte70Pn8Er75IhNbp8cB8U3MX-PNnN5zgP9lORReRy0rEI3wPZRRUIVtSEHMB7ABOACWYDhKAOBBqjdXhxWoZxpVlNgsCgGgcBBDpVQAfg1HkCgAGigSi3ENIdaPyBjKPnW1OR9NiOO3Y9d14wtDn468QzPcM+MYuNkUyJMcTxLACQEIktS4Djfy-Gk2NrbIONAoCI3pOsm3kMkUFCWTnygRwXDgaokAoURCmslESAAH3RTFFNTARVUzc5RHESRpFQZglQ6DVmNHIcuMXCgfQE4MN2EZKT1vcM3KgLTwW-Qyq0UfBLKgVYpBkeRgokcrUFIyc3QCggSrK6QACZmyq0KBFqsiGocWQACIAAkwCQO4BoY+K7SXYR5AGhg93AAadSAA&html=Q&css=Q)

**Example 1:** 

Library source code

**Example 1:** 

https://github.com/nfdi4plants/ISADotNet/blob/ea4e1cefdceb8b0899f029409ee5ac4b003268f5/src/ISA/ISA/ArcTypes/ArcTable.fs#L166

**Example 1:** 

https://github.com/nfdi4plants/ISADotNet/blob/ea4e1cefdceb8b0899f029409ee5ac4b003268f5/src/ISA/ISA/ArcTypes/ArcAssay.fs#L108

### Expected and actual results

I would expect NamedParams to work in this case. Not sure where something is going wrong

### Related information

* Fable version: `dotnet fable --version`: **4.1.4**
* Operating system: Windows 11

**Comment by Freymaurer** [comment] 2023-06-27 13:37
I want to use `[<NamedParams>]` to avoid passing void if not all params are given.

```javascript
// Without NamedParams
export const assay = ArcAssay.create();

export const assay2 = ArcAssay.create("Hello", void 0, "MyType");
```

```javascript
// With NamedParams
export const assay = ArcAssay.create();

export const assay2 = ArcAssay.create({
    id: "Hello",
    measurementType: "MyType",
});

```

Both taken from Fable.Repl

**Comment by MangelMaxime** [comment] 2023-06-27 17:57
Ok, we will have to wait other maintainer opinion on this one.

`NamedParams` and `ParamObject` are a new addition made by @alfonsogarciacaro. I don't know what is position is on this subject.

**Comment by Freymaurer** [comment] 2023-06-28 08:00
Update for the REPL. It does in fact not run correctly. I tried printing the created assays to the console and it does not work, unless i remove the `ArcAssay.create()`. So it also seems to error, without recognizing it errored.

**Comment by MangelMaxime** [comment] 2023-06-28 12:35
Yes `ArcAssay.create()` doesn't work.

This is because, it generates `ArcAssay.create()` instead of `ArcAssay.create({})`.

Meaning that there are no object to desconstruct.

If you provide at least 1 argument, then this works because the object will be initialised.

**Comment by Freymaurer** [comment] 2023-07-12 07:16
> Ok, we will have to wait other maintainer opinion on this one.

> NamedParams and ParamObject are a new addition made by @alfonsogarciacaro. I don't know what is position is on this subject.

Any new information on this? 😄  This would be a very nice option for libraries which should be usable on multiple languages.

**Closed** 2023-08-08 20:28 UTC

**Comment by MangelMaxime** [comment] 2023-08-09 14:30
@alfonsogarciacaro @ncave 

In order to fix this issue, I had make changes in Fable.AST

Does it means we need to ask for a re-release of Feliz.CompilerPlugins ?

**Comment by DunetsNM** [comment] 2024-05-14 03:49
addition of `Attributes : Attribute seq` to `MemberRefInfo`  broke json deserialization in Util.fs  : 

> Json.readWithStringPool<(string * Fable.InlineExpr)

it now  throws

>  error EXCEPTION: Deserialization of interface types is not supported. Type 'Fable.AST.Fable.Attribute'. Path: $[0] | LineNumber: 0 | BytePositionInLine: 2.
>    at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
> 

I don't have a small repro just yet - will add a separate issue when I have it (seems to be related to using `--precompiledLib` flag) , but root cause is pretty obvious:   Attribute is an interface which also has `ConstructorArgs: obj list` i.e. no chance it can serialize. 

It fails even though in my `inline_exprs_0.json` file all Attributes collections are empty. Good news it has only one usage: literally to check presence of  "Fable.Core.ParamObjectAttribute", so it's easy to fix by replacing  `Attributes: Attribute seq` with `AttributeNames: string seq` or even `HasParamObjectAttribute: bool`

Lesson to extract here is to keep coupling between types at minimum
