### ISSUE TITLE
Error when using KeyValueList with static functions

### ISSUE THREAD

**Issue by rkosafo** [fable-compiler/Fable#543] opened 2016-11-13 07:49 UTC
### Description

I copied some code over from a previous project and realized that the project is breaking. The reason is that it appears `DU`s with `KeyValueList` attributes are erased together with all static functions. At such, any static methods on them are wrongly translated. The call is made on `fable-core/Util/Any`. 

Since `Any` supplies some functions (`Equals`), is it possible to identify when a call to a "non standard" function is made so that we get an error at compile time instead of at runtime? 

### Repro steps

    module Mojo =
      [<Fable.Core.KeyValueList>]
      type Items = 
        | Jojo of string 
        | Jojojo of int 
        | Jojojojo of float with
        static member withDefaults v = [ Jojo "Caption"] //this is lost
      let mojojojo () = Items.withDefaults[ Jojojo 5]  //this is an error

### Expected behavior

Working code or a nice compile time error

### Actual behavior

It is translated to the code below which gives a runtime error

	var Mojo = function (__exports) {
	  var mojojojo = __exports.mojojojo = function mojojojo() {
	    return Any().withDefaults({
	      jojojo: 5
	    });
	  };

### Known workarounds

Do not add functions to such `DU`s. Write the functions separately

### Related information 

* Fable Version: 0.7.5-alpha.34
* .NET Runtime, CoreCLR or Mono Version
* Operating system

**Comment by alfonsogarciacaro** [comment] 2016-11-13 08:03
I need to do something with this :/ Types with `Erase`, `StringEnum` or `KeyValueList` attributes are **erased** in the generated JS code, so they don't have the semantics of normal DUs and can only be used to define arguments for JS functions.

I'd like to add compile time errors for this, but the problem is there're many situations where the erased types may fail so covering everything would entail polluting Fable's internal code with lots of checks here and there. I haven't yet found an elegant solution to this problem :( There's a similar discussion in #507.

Probably the best thing that can be done at the moment is improving the documentation to make it clear erased types cannot be used for anything else that their specific purpose.

**Comment by rkosafo** [comment] 2016-11-13 08:51
Yeah. I think a page indicating the areas where the fable output differs from the expectation will be helpful, particularly to new users. An error will however help particularly for existing users. I currently have some four apps with fable in production planning to upgrade when fable reaches 1.0. It would have been nice if they just blow up at compile time rather than at runtime. The changes however should be few so the documentation should still be fine.

Is there any documentation on the difference between the current stable version and the alpha?

**Comment by alfonsogarciacaro** [comment] 2016-11-13 11:05
Wow, you've four Fable apps in production? It'd be lovely to read a post about your experience :)

About the 0.7 migration, there's a summary in #522, but I still need to write a more detailed post. Hopefully it should be ready next week :+1:

**Comment by alfonsogarciacaro** [comment] 2016-12-04 19:13
[Fable 0.7 is released](http://fable.io/blog/Introducing-0-7.html) and I tried to add warnings for erased types to prevent confusions like this, so I'm closing the issue for now. But please feel free to reopen it if you've any other question.

**Closed by alfonsogarciacaro** 2016-12-04 19:13 UTC
