### ISSUE TITLE
Declarations flag generates invalid .js require when importing Fable.Import.React

### ISSUE THREAD

**Issue by MaxWilson** [fable-compiler/Fable#388] opened 2016-09-07 23:38 UTC
### Description

When using React, --declaration flag generates reference to non-existent file causing downstream failures (webpack in my case).
### Repro steps

1.) Make sure your .fsproj contains a reference to Fable.Import.React, installed via npm:

```
    <Compile Include="node_modules/fable-import-express/Fable.Import.Express.fs" />
    <Compile Include="node_modules/fable-import-react/Fable.Import.React.fs" />
    <Compile Include="node_modules/fable-import-react/Fable.Helpers.React.fs" />
    <Compile Include="source\Components.fs" />

```

2.) Make sure one of your files e.g. Components has references to Fable.Import.React:

```
module R = Fable.Helpers.React
open R.Props
open Fable.Import.React
```

3.) Run fable --declarations
### Expected behavior

Generated output has only valid js references in it
### Actual behavior

Generated .js file has spurious reference to a non-existent file called "Fable.Import.React-xxxxxxxxx".

`var _FableImport = require("./../fable_external/Fable.Import.React-2067647680");
`
### Known workarounds

If you delete the bogus _FableImport variable and then run webpack everything just works--the bogus variable is not used.
### Related information
- Fable Version 0.5.5
- .NET Runtime 4.6
- Operating system Windows 10
- Additional repro info:

See https://github.com/MaxWilson/Beast/tree/AddLayout for example project. Check out the project and run "fable --declarations" for an immediate webpack failure: 

_ERROR in ./temp/source/Components.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./../fable_external/Fable.Import.React-2067647680 in D:\code\Beast\temp\source @ ./temp/source/Components.js 16:19-79_

**Comment by alfonsogarciacaro** [comment] 2016-09-09 09:23
Thanks a lot for reporting the issue and creating a reproducible environment. The support for declaration files is still experimental and hasn't been thoroughly tested, but I'll clone your project and investigate the problem.

Cheers!

**Comment by alfonsogarciacaro** [comment] 2016-12-04 20:09
Closing the issue for now as `fable-import-react` has been deprecated in favour of `fable-react`. Also `--declaration` is still experimental and I'd rather keep it as is because it requires a lot of work and there's been no much response from the community about it.

Please feel free to reopen the issue if you any comment.

**Closed by alfonsogarciacaro** 2016-12-04 20:09 UTC
Labels: bug
