### ISSUE TITLE
Fable.SignalR.Elmish 0.11.3 + Fable 3.1.12  => Uncaught TypeError: tree is undefined

### ISSUE THREAD

**Issue by davedawkins** [fable-compiler/Fable#2419] opened 2021-03-23 14:37 UTC
Downgrading Fable to 3.1.11 fixes the issue. 

Reproduction project attached: [fable_3_1_12_json_bug_clean.zip](https://github.com/fable-compiler/Fable/files/6190399/fable_3_1_12_json_bug_clean.zip)

To build:
```
% dotnet tool restore
% npm install
% npm run start 
```

Point browser at http://localhost:8080, and open browser console.

You should see an error like this:

```
Uncaught TypeError: tree is undefined
    Convert_usingFable3 webpack:///./src/App/.fable/Fable.SimpleJson.3.18.1/Json.Converter.fs.js?:95
    <anonymous> webpack:///./src/App/.fable/Fable.SimpleJson.3.18.1/Json.Converter.fs.js?:103
    <anonymous> webpack:///./src/App/.fable/Fable.SimpleJson.3.18.1/Json.Converter.fs.js?:2102
    js http://localhost:8080/bundle.js:938
    __webpack_require__ http://localhost:8080/bundle.js:20
    <anonymous> webpack:///./src/App/App.fs.js?:19
    js http://localhost:8080/bundle.js:1526
    __webpack_require__ http://localhost:8080/bundle.js:20
    <anonymous> webpack:///multi_(webpack)-dev-server/client?:2
    0 http://localhost:8080/bundle.js:1537
    __webpack_require__ http://localhost:8080/bundle.js:20
    <anonymous> http://localhost:8080/bundle.js:84
    <anonymous> http://localhost:8080/bundle.js:87
bundle.js line 938 > eval:95:9
    Convert_usingFable3 webpack:///./src/App/.fable/Fable.SimpleJson.3.18.1/Json.Converter.fs.js?:95
    <anonymous> webpack:///./src/App/.fable/Fable.SimpleJson.3.18.1/Json.Converter.fs.js?:103
    <anonymous> webpack:///./src/App/.fable/Fable.SimpleJson.3.18.1/Json.Converter.fs.js?:2102
    js http://localhost:8080/bundle.js:938
    __webpack_require__ http://localhost:8080/bundle.js:20
    <anonymous> webpack:///./src/App/App.fs.js?:19
    js http://localhost:8080/bundle.js:1526
    __webpack_require__ http://localhost:8080/bundle.js:20
    <anonymous> webpack:///multi_(webpack)-dev-server/client?:2
    0 http://localhost:8080/bundle.js:1537
    __webpack_require__ http://localhost:8080/bundle.js:20
    <anonymous> http://localhost:8080/bundle.js:84
    <anonymous> http://localhost:8080/bundle.js:87
```

See `src\App\App.fs` for details. Reproduced here for convenience

## App.js
```fs
module App

open Browser.Dom

open Fable.SignalR.Elmish

// Using Fable 3.1.12
// ------------------
// Making this symbolic reference into SignalR.Elmish is enough to induce the error.
// I'm using "unbox" to stop compiler warnings. Note that the init() function is never invoked.
//
// Error is seen in console output:
//      Uncaught TypeError: tree is undefined
//
// To prevent the error, either:
// 1. Comment the init() function out, or
// 2. dotnet tool install fable --version 3.1.11
//
let init() = unbox Cmd.SignalR.connect


let app = document.querySelector("#app")

app.innerHTML <- "<h1>Hello World</h1"

```

**Comment by Zaid-Ajaj** [comment] 2021-03-23 16:14
Hi @davedawkins this looks like a Fable.SimpleJson error as reported [here](https://github.com/Zaid-Ajaj/Fable.SimpleJson/issues/64)

**Comment by davedawkins** [comment] 2021-03-23 18:38
HI @Zaid-Ajaj , I see you made a fix for the related issue, should I test this project against the fix? If so, tell me what to update please. If it passes we can just close this issue.
Cheers

**Comment by Zaid-Ajaj** [comment] 2021-03-23 19:15
@davedawkins you can either 
 - wait for a new release of this library that uses latest Simple JSON
 - install latest Simple JSON yourself
 - downgrade Fable compiler version to 3.1.5

**Comment by davedawkins** [comment] 2021-03-23 19:39
I'm fine with 3.1.11. I just wanted to clear this issue from your list.

**Comment by Zaid-Ajaj** [comment] 2021-03-23 20:37
You can close it now I think, the issue is resolved in SimpleJson and downstream libraries need to update it

**Closed** 2021-03-23 20:40 UTC

**Comment by alfonsogarciacaro** [comment] 2021-03-23 23:33
Thanks a lot for the quick fix @Zaid-Ajaj! I was afraid I had to unlist another version because I had broken everything again 😅

**Comment by davedawkins** [comment] 2021-03-23 23:40
Yes, thanks @Zaid-Ajaj !
