### ISSUE TITLE
Primary constructor of types from signature files (.fsi) are mangled

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#571] opened 2016-11-30 01:28 UTC
Given the following project:
```
//--- test.fsi ---
module M
type Test =
    new : bool -> Test      // <-- here is what's causing it
    member Status: bool
```
```
//--- test.fs ---
module M
type Test(flag:bool) =
    member x.Status = flag
```

```
//--- project.fsx ---
#load "test.fsi"
#load "test.fs"

[<EntryPoint>]
let main argv =
    let t = M.Test(true)
    printfn "Status: %A" t.Status
    0
```
Here the constructor call will be generated as:
`  const t = _test.Test[".ctor"](true);`

which causes a runtime error. It should be:
`  const t = new _test.Test(true);`

The runtime error does not happen if the constructor definition is not used.

**Comment by alfonsogarciacaro** [comment] 2016-11-30 22:46
I haven't tested Fable that much with .fsi files, probably this needs some work.

Sometimes it seems F# specs are endless... :/

**Comment by ncave** [comment] 2016-11-30 23:01
I hear you, unfortunately we can't call the constructor without that constructor definition. The only option in that case is to not use signature files at all, which is a steep limitation for compiling existing code bases.

I was hoping that it's something simple that you can just spring out of your magic hat ;)

**Comment by alfonsogarciacaro** [comment] 2016-12-01 01:12
Ok, I've investigated about this and it's not simple ;)

The problem happens because when using the .fsi, `meth.IsImplicitConstructor` fails (I guess this is because the method declaration in the .fsi file is taken, where there're no implicit constructors), so [this line](https://github.com/fable-compiler/Fable/blob/21b00ec75d83c3d66e4e38b0f760194a8f259439/src/fable/Fable.Compiler/FSharp2Fable.Util.fs#L226) doesn't evaluate to true.

This is a problem because JS only accepts one single constructor and the other must be compiled as static methods. I have tried a hack by checking that the method is the first of all constructors in the type and this seemed to work but then I had problems with the structs we added recently in #568 because they can have constructors but no implicit constructor (which must be generated automatically).

I haven't found a way to match the constructor reference to the actual implementation either :/

Can you please open an issue in FCS asking that `.IsImplicitConstructor` must evaluate to true also when using signature files?

**Comment by ncave** [comment] 2016-12-01 03:20
Hmm, for some reason my experience is different. The Test class gets compiled the same exact way with or without the test.fsi, and generates the same exact ast and js. The difference caused by including the .fsi is at the calling site (in project.fsx), where it does change the ast of the constructor call quite a bit to one that is perhaps not supported well by Fable atm. I agree though that it probably should not result in a different ast, but it does. I've attached the results with and without including #load "test.fsi"
[with_fsi.zip](https://github.com/fable-compiler/Fable/files/623637/with_fsi.zip)
[without_fsi.zip](https://github.com/fable-compiler/Fable/files/623638/without_fsi.zip)

**Comment by ncave** [comment] 2016-12-01 14:14
Thank you for investigating, I think the simplest work-around for now is to add an explicit constructor to call the implicit one:
```
module A
type Test(flag:bool) =
    new(flag:bool, _) = Test(flag) // <-- added an explicit constructor here
    member x.Status = flag
```
Not the prettiest solution but it works.

**Comment by alfonsogarciacaro** [comment] 2016-12-01 17:26
I would still ask in FCS repo about this. It should be possible to go from the signature declaration of an entity to the implementation declaration, but I couldn't find an easy way to do this.

**Comment by alfonsogarciacaro** [comment] 2016-12-01 21:25
Another solution would be just to filter out `.fsi` files when running the F# type checker.

**Comment by ncave** [comment] 2016-12-01 21:51
Idk, sometimes .fsi files are needed so maybe not a good idea to leave them out completely.

I kind of like your hack above (to check if it's the first constructor, and do the rest as static). The 'no implicit constructor' for value types is kind of the same as the one in #573 which is not supported yet, so maybe it won't be a problem.

**Comment by alfonsogarciacaro** [comment] 2017-05-11 21:12
@ncave Sorry, I lost track of the issue?, commit?, PR? where we discussed a possible solution for this. Do you know where was it? Did you have a look?

**Comment by ncave** [comment] 2017-05-13 06:44
@alfonsogarciacaro See #843.

**Comment by alfonsogarciacaro** [comment] 2017-05-13 12:58
There it was, thank you!

**Comment by alfonsogarciacaro** [comment] 2018-03-04 11:10
I was thinking of a way in Fable 2 to solve this, but when testing I noticed that latest FCS seems to identify correctly implicit constructor even if they come from a signature file. I create a repro here: https://github.com/alfonsogarciacaro/TypeProviderTest/tree/implicit-cons

Should we close this? Can you reproduce with Fable 1.3.10?

**Comment by ncave** [comment] 2018-03-04 22:34
@alfonsogarciacaro Sure, close it. If it works now, I'll get rid of the work-around secondary constructors in FCS in the next iteration.

**Comment by alfonsogarciacaro** [comment] 2018-03-04 22:48
Perfect, let's keep it open until Fable 2 alpha is released and maybe add a test with your code above to make sure there's no regression :+1:

**Comment by alfonsogarciacaro** [comment] 2018-12-12 00:50
This should be working in Fable 2. Please reopen if not.

**Closed by alfonsogarciacaro** 2018-12-12 00:50 UTC
