### ISSUE TITLE
Cannot resolve trait error

### ISSUE THREAD

**Issue by twm-aspl** [fable-compiler/Fable#2809] opened 2022-02-07 03:09 UTC
### Description

In certain situations, using the infix operators for the Aether optics libary (e.g. (^.)) is generating "Cannot resolve trait call op_HatDot" errors.

### Repro code

[https://github.com/twm-aspl/WrongOverloadSelected2](https://github.com/twm-aspl/WrongOverloadSelected2)

See comments line 50 of AttemptRepro.fs.

### Expected and actual results

Expected: 
No errors.

Actual: 
"Cannot resolve trait call op_HatDot" errors
*Also* unrelated code using the (^.) operator that previously compiled and was not changed now also shows compiler errors.

### Related information

Could be a regression here [750](https://github.com/fable-compiler/Fable/issues/750), and
Here [2101](https://github.com/fable-compiler/Fable/issues/2101)

* Fable version: 3.6.3
* Operating system: Mac OS

**Comment by alfonsogarciacaro** [comment] 2022-02-08 13:02
Thanks a lot for the report @twm-aspl! I tried cloning the repo you linked, run `dotnet tool restore && dotnet run` and then uncommenting the lines as per the instruction but I couldn't reproduce the error, everything seemed to work fine.

![screencast](https://user-images.githubusercontent.com/8275461/152992309-46213676-a396-415c-854d-a18c4235cf7e.gif)

**Comment by twm-aspl** [comment] 2022-02-10 04:04
Thanks very much for looking into this. I've just pushed a new version that reproduces a second (possibly related) issue where I suspect the wrong overload is being selected. The "fableOpticsTest()" function runs fine on the server, but causes a type error on the client.

**Comment by alfonsogarciacaro** [comment] 2022-02-16 06:49
Wow, this has been much trickier than I expected. I think I've fixed it in #2823. At least your code compiles, could you please add an assertion so we can convert it into a test and avoid regressions? @twm-aspl Thanks!

@gusty When investigating this, I realized that Fable was matching the generics wrong when resolving multiple nested inlined functions. Hopefully when merging the PR some of the issues you had are fixed too :)

**Comment by gusty** [comment] 2022-02-16 07:29
Cool, I'll find some time to re-test everything and I see where we stand now ;)

Thanks for the update.

**Comment by twm-aspl** [comment] 2022-02-17 00:00
@alfonsogarciacaro thanks for all your work on this!  I created a stand-alone module **GenericsMatching** to reproduce the "wrong overload selected" conditions with an assertion based test as requested. For your consideration as part of regression test suite.

**Comment by twm-aspl** [comment] 2022-02-17 23:57
I can confirm 3.7.1 fixes the compilation issues and works as expected with the WrongOverloadSelected2 repo.

However, while my main solution now compiles OK, it's having issues with webpack and the source path generated by Fable in the "import ..." statements. Apologies in advance if this is a local configuration issue (I've recently upgraded webpack, and my knowledge of the inner workings of this is limited), but the errors are local to code involved with #2809.

```
import { FailureTree, ViewTree$3 } from "../../FormletLibrary/Core.fs.js";
import { FailureTree_Join_Z7D595040 } from "./Core.fs.js";                       // path should be the same path as the line above
```

If I manually correct the paths, everything works.

Any suggestions?

**Comment by alfonsogarciacaro** [comment] 2022-02-21 01:39
Ah, no, this probably has not to do with your configuration but with Fable not fixing the import path when inlining the function. I'll check, sorry for that.

**Comment by alfonsogarciacaro** [comment] 2022-02-22 03:30
@twm-aspl I think I found the issue though unfortunately I couldn't reproduce your exact error. Could you please try with Fable v3.7.2 and check if it works now? Thanks!

**Comment by twm-aspl** [comment] 2022-02-22 04:04
@alfonsogarciacaro that works - thank-you!

**Comment by alfonsogarciacaro** [comment] 2022-02-22 04:05
Awesome, thanks for confirming!

**Closed by alfonsogarciacaro** 2022-02-22 04:05 UTC
