### ISSUE TITLE
For "AbstractClass" generated code changed ??

### ISSUE THREAD

**Issue by PvlD** [fable-compiler/Fable#2380] opened 2021-02-12 18:10 UTC
For [AbstractClass]  generated code changed ( not correct ).
In previous version it was the same as for  interface.

![image](https://user-images.githubusercontent.com/10778065/107805520-76462400-6d33-11eb-810c-25285018c595.png)

**Comment by alfonsogarciacaro** [comment] 2021-02-13 00:06
Hi @PvlD! In Fable 3 we introduced mangling of attached members to avoid name clashes. For interfaces this is opt-in through the Mangle attribute. For abstract classes I made it automatic because they're used less often for interoping. However, when the classes are global or imported they are not mangled because it's assumed they come from JS. In your case it seems Fable gets confused because the class itself does not have the Import attribute. If you don't need to inherit AExports, I would recommend using an interface instead. If you do, can you try adding the Import or Global attribute to the class itself? Btw, I would also recommend not using **both** the Global and Import attributes at the same time as with LogA, because they have different behavior (don't remember exactly which one will be winning in this case).

**Comment by PvlD** [comment] 2021-02-13 00:39
Thank you for clarification.
I just state  that  code generation is changed.

**Comment by alfonsogarciacaro** [comment] 2021-07-12 02:29
Closing as I understand the issue is solved, please reopen if there are further questions.

**Closed by alfonsogarciacaro** 2021-07-12 02:29 UTC
