### ISSUE TITLE
Record type with element a polymorphic function

### ISSUE THREAD

**Issue by filangel** [fable-compiler/Fable#756] opened 2017-03-19 20:29 UTC
### Description

TypeError for record type with element a polymorphic function. When a new instance of the record is constructed, It gives a runtime error `Uncaught TypeError: parser.parseFunc is not a function`.

### Repro code

```F#
    type Pos = { lineNo : int ; tokenNo : int }

    type InitState = { lineList : List<Token>[] ; position : Pos }

    type Outcome<'a> =
        | Success of 'a
        | Failure of Pos * string

    type Parser<'T> =
        { parseFunc : (InitState -> Outcome<'T * InitState>)
        pLabel:  string }

    let setLabel parser newLabel = 
        let newInnerFn input = 
            match parser.parseFunc input with
            | Success s -> Success s 
            | Failure (parPos, err) -> Failure (newLabel,err, parPos)
        {parseFunc=newInnerFn; pLabel=newLabel}
```

The function `setLabel` passes type check from Fable Compiler but throws a runtime `TypeError`.

### Expected and actual results

Running F# compiler in the CLI passes type check and compiles.

### Related information 

* fable-compiler version: 0.7.50
* fable-core version: 0.7.29
* Operating system: macOS 10.12.3

**Comment by alfonsogarciacaro** [comment] 2017-03-20 09:16
@filangel These cases are usually fixed by adding type annotations to the function signature, this is usually necessary when you're trying to access a member with `.` notation and the type checker hasn't had an opportunity to infer the type yet.

```fsharp
let setLabel (parser: Parser<'T>) newLabel = 
```

**Comment by filangel** [comment] 2017-03-20 09:54
@alfonsogarciacaro I changed all the function signatures but still have the same error.

**Comment by Zaid-Ajaj** [comment] 2017-03-31 20:16
@filangel I am not able to reproduce your issue, I am missing definition of type `Token`

**Comment by filangel** [comment] 2017-04-01 08:46
@Zaid-Ajaj 
```F#
type Token =
        | TokDash
        | TokEquals
        | TokNewLine
        | TokError of string
        | TokEOF
        | TokLiteral of int
```

**Comment by Zaid-Ajaj** [comment] 2017-04-01 17:09
@filangel your program does not compile: 
```fsharp
    let setLabel parser newLabel = 
        let newInnerFn input = 
            match parser.parseFunc input with
            | Success s -> Success s 
            // this part gets compile error because Failure only takes "Pos * string" 
            // you are giving it "string * string * Pos"
            // are you propagating the "newLabel" to the error message?
            | Failure (parPos, err) -> Failure (newLabel,err, parPos)
        {parseFunc=newInnerFn; pLabel=newLabel}
```
This version of it does compile:
```fsharp
let setLabel parser newLabel = 
    let newInnerFn input = 
        match parser.parseFunc input with
        | Success s -> Success s 
        | Failure (parPos, err) -> Failure (parPos, err)
    { parseFunc = newInnerFn; pLabel = newLabel }
```
And since `newInnerFunc` is just `parser.parseFunc` you can refactor it to this:
```fsharp
let setLabel parser newLabel = { parser with pLabel = newLabel  }
```
It compiles fine and without calling `setLabel` I get no runtime errors when opening the html page, here's my test project, it is just the basic Fable template + your code:

[TestParser.zip](https://github.com/fable-compiler/Fable/files/887824/TestParser.zip)

- Unzip
- run `dotnet restore` to get the compilers (make sure you have dotnet cli tools installed)
- run `npm install` to get webpack and runtime dependencies
- run `npm run start-dev` to start fable compiler server and webpack dev server
- navigate to localhost:8080

**Comment by alfonsogarciacaro** [comment] 2017-05-11 20:59
Thanks a lot for your help @Zaid-Ajaj!

**Closed** 2017-05-11 20:59 UTC
