### ISSUE TITLE
inconsistencies with arrays

### ISSUE THREAD

**Issue by runefs** [fable-compiler/Fable#1509] opened 2018-08-02 12:44 UTC
### Description

I would expect arrays to behave consistently regardless of whether they are emitted or written in F#

### Repro code
```
[<Emit(" [1] ")>]
let arr : int []  = jsNative

[|1|] = [|1|] // is true
arr = [|1|] // is false
```

### Expected and actual results
I'd expect both to have the same result. JS semantics would result in `false` whereas F# semantics would make both `true`. I would suggest the latter

###Related information
using docker image: nojaf/fable:latest

**Comment by MangelMaxime** [comment] 2018-08-02 12:51
F# use `TypedArray` when possible to improve performance. 

```fs
open Fable.Core
open Fable.Core.JsInterop
open Fable.Import

[<Emit(" [1] ")>]
let arr () : int []  = jsNative

JS.console.log([|1|] = [|1|]) // is true
JS.console.log(arr () = [|1|]) // is false
```

Generated JS:

```js
import { equals } from "fable-core/Util";
console.log(equals(new Int32Array([1]), new Int32Array([1])));
console.log(equals([1], new Int32Array([1])));
```

**Comment by alfonsogarciacaro** [comment] 2018-08-02 13:07
[This should be fixed in Fable 2](http://fable.io/repl2/#?code=open%20Fable.Core%0A%0A%5B%3CEmit(%22%20%5B1%5D%20%22)%3E%5D%0Alet%20arr%20%3A%20int%20%5B%5D%20%20%3D%20jsNative%0A%0Aarr%20%3D%20%5B%7C1%7C%5D%20%7C%3E%20printfn%20%22%25b%22) :)

**Comment by Zaid-Ajaj** [comment] 2018-08-02 13:50
@alfonsogarciacaro Daaamn repl2 is already working? and with elmish samples too, talk about next level fancy stuff, this is amazing :heart:

**Comment by alfonsogarciacaro** [comment] 2018-08-02 13:54
@Zaid-Ajaj Sshh, it's a secret :wink: Yes, repl2 is working and it features several of your Elmish samples. It'll be announced shortly :+1:

**Comment by matthid** [comment] 2018-08-02 14:03
@alfonsogarciacaro Only here to tell you that the repl is indeed awesome! (just one minor nit I noticed while using no-script blocking `nupkg.com`: The error reporting could be a bit better)

**Comment by StachuDotNet** [comment] 2018-08-02 14:04
![image](https://user-images.githubusercontent.com/906686/43588881-74635530-963b-11e8-9e27-39761ee5af4d.png)

**Comment by alfonsogarciacaro** [comment] 2018-08-02 20:02
@matthid Sorry, do you mean when JS is disabled in the browser? How would you show the error in that case, with an HTML tag? Could you [please send a PR](https://github.com/fable-compiler/repl2) for that?

**Comment by matthid** [comment] 2018-08-02 20:37
Seems like I cannot reproduce anymore but I had this configuration:
![image](https://user-images.githubusercontent.com/1866463/43609458-5adec766-96a4-11e8-959f-35ee8a9a3110.png)
and the samples stayed blank. You probably can probably ignore me as noscript is really uncommon nowadays. Anyway it seems blocking the script no longer works and my browser/the extension is not doing what I want. So now it always works...

**Comment by runefs** [comment] 2018-08-03 08:09
Ah my lack of js knowledge is the source of the problem, it seems to be consistent

**Comment by runefs** [comment] 2018-08-03 08:14
when I closed and the page refreshed I could see the discussion had continued. With the Int32Array comment I find the behavior to be consistent. I emitted a different type of object than what I should have expected fable to compile to. However since you continued the discussion. I'd leave it up to you whether it should be closed

**Comment by alfonsogarciacaro** [comment] 2018-08-03 12:55
Thanks for confirming @runefs. Ok, let's close this and continue the discussion if necessary in the repl2 repo :)

**Closed** 2018-08-15 07:45 UTC
