### ISSUE TITLE
FsToolkit.ErrorHandling errors on 4.0.0-theta-015

### ISSUE THREAD

**Issue by TheAngryByrd** [fable-compiler/Fable#3259] opened 2022-11-09 00:11 UTC
### Description

:wave: I'm going thru the process of [updating FsToolkit.ErrorHandling to F# 7](https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/193) however, I'm getting this error when compiling and running the tests. 

```
Started Fable compilation...
Fable compilation finished in 2605ms                                    

.\tests\FsToolkit.ErrorHandling.Tests\Expect.fs(50,28): (50,44) error FABLE: Cannot get type info of generic parameter $a. Fable erases generics at runtime, try inlining the functions so generics can be resolved at compile time.
Compilation failed
Finished (Failed) 'RunFableTests' in 00:00:17.2451839
```

This code was working before, I'm not sure what changed.  I tried inlining a few of the functions in the module but it didn't seem to change anything.

Any pointers would be helpful! Thanks :)

### Repro code

[PR of FsToolkit](https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/193)

To run build either `build.cmd` or `build.bash` should initiate it. 

### Expected and actual results

Please provide the expected and actual results.

### Related information

```
dotnet fable --version
4.0.0-theta-015
```

* Fable version: `dotnet fable --version`
* Operating system

**Comment by TheAngryByrd** [comment] 2022-11-09 00:16
Well I guess inlining _everything_ in the file seems to work. I don't mind doing it but feels like a weird change to me.  Feel free to close if this is by design.

**Comment by alfonsogarciacaro** [comment] 2022-11-09 12:55
Thanks a lot for reporting @TheAngryByrd! Our goal is to make every code compilable with Fable 3 also compilable with Fable 4 as-is, so ideally we shouldn't need to introduce code changes only for Fable 4.

Although I'm surprised about two things:
- The need to inline functions to get type info from generics has been a Fable requirement since the beginning, so you should have seen it in Fable 3 too.
- I don't see any function in Expect.fs requiring type info from a generic so the error shouldn't be raised 🤔 Do you know of any other place in the code that uses type info from generics?

**Comment by TheAngryByrd** [comment] 2022-11-09 13:05
> I don't see any function in Expect.fs requiring type info from a generic so the error shouldn't be raised 🤔 Do you know of any other place in the code that uses type info from generics?

No I do not. I haven't tried, but looking again, I wonder if it's related to the `sprintf "%A"` type code?

**Comment by alfonsogarciacaro** [comment] 2022-11-09 13:52
Thanks to your link I could reproduce and found the issue: it's the `same` function, because Fable.Mocha.Expect.equal [does get the type info from the generic](https://github.com/Zaid-Ajaj/Fable.Mocha/blob/6fd49e63e49d8809c6a6cbd2619020ab59297b9c/src/Mocha.fs#L102). Only inlining that function seems to help.

Still, I'm not sure why this issue didn't happen before and why the line number in the error log is so off. Maybe it's because of the conditional compilation with `#if FABLE_COMPILER`, but I thought the actual line numbers were kept in that case.

**Comment by TheAngryByrd** [comment] 2022-11-09 16:31
> I'm not sure why this issue didn't happen before

I was on [3.7.1](https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/8a6c9c97f59a25f129697312aeb61d7795cfbf1b/.config/dotnet-tools.json#L12) previously.  Perhaps that wasn't introduced yet? 🤷‍♂️

**Comment by alfonsogarciacaro** [comment] 2022-11-19 10:18
> I was on [3.7.1](https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/8a6c9c97f59a25f129697312aeb61d7795cfbf1b/.config/dotnet-tools.json#L12) previously. Perhaps that wasn't introduced yet? 🤷‍♂️

I'd have to build with 3.7.1 to see what's the code compiled, but I doubt it because resolving generics at compile time has been a feature since the beginning.

In any case, I've sent a PR to try to fix the build, including potential problems with the SDK. Can you please check? https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/196

**Closed** 2023-05-02 15:34 UTC
