### ISSUE TITLE
Fable watch mode should allow to delete files from fsproj

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#1335] opened 2018-01-26 12:34 UTC
Watch mode is awesome! And if you modify the fsproj and add a new file, then fable picks it up and compiles it. Unfortunately if you yank a file then watch mode is broken.

**Comment by alfonsogarciacaro** [comment] 2018-01-26 12:36
Hmm, that's weird. Every time you edit .fsproj the whole project is recompiled again, I'll try to reproduce it.

**Comment by alfonsogarciacaro** [comment] 2018-12-12 10:30
I cannot reproduce with latest `fable-loader` and `fable-compiler`. Is this still happening to you?

**Comment by alfonsogarciacaro** [comment] 2018-12-12 22:17
Sorry, I'll close the issue as I cannot reproduce. If it's still a problem for you, could you please reopen giving more details? (fable-loader or splitter, versions, steps to reproduce, etc)

**Closed by alfonsogarciacaro** 2018-12-12 22:17 UTC
Labels: waiting-feedback
