### ISSUE TITLE
Static member turns into instance member

### ISSUE THREAD

**Issue by goswinr** [fable-compiler/Fable#3857] opened 2024-06-19 07:55 UTC
A static member turns into an instance member when defined in an interface:
see [REPL](https://fable.io/repl/#?code=FAewDgpgdgBAYgQwEYBsIDoDCIBOFjADEUIA7gjrAEQDMArPVTAPTMwBmuMArgM4CWUAOYxeAFwRj+AYxjJxOBNLEExAT0gwAkkgpwQIGAF5gMMzFPnxkmXKQKlYmLpwAuUWJyChls77sOyvAG7greBADaADwAgmIS0gAWALIQALZIEDi8AHwAusDqmgBCCABeABQAlMbm-v7WUrJp6Zk4cnCCEADKEk2pGVm1VEzmrDBiify8MNIgaWD8aDPsXej15jCCYlnsShDaLvqGpPyT-psXVn22LYPtLrUwIyxsYtyUM9uGgtZQ0gc7m0YABCMFXPybTZAoaTaboY7DUZQiwovxAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8ARAMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3BJAoATgGcCTGmABm5ABwssOYAEJy5XLona6pMJl3aJrEqV0AuJSUJNC4AOgArXTQkKEZtMK4CJS5SCCVdDji0ciiAAQBGMLMwgoB2JTQ6XWVM7LCIOnCoy2AM51cwK2xgJxc3Dy8fMDIAoJDm6Nj4xOTU9Lq6HPyikvKlAHckACNK6uUt7YamyN1W9v6uzHtuxw6BsBEkVggONBooMRhMOghSDm07kWaCimGM2g4EGIIz8gWCoVOMTiDASSWU8wyWSWuV0hWKpQqAGokLooW0+p14G0QKgMAhgNs3kJbsAqgwfmhWChSBQpDwUE0kNpzmyqUpGWhmfSVJBYHAgA&css=Q)
![image](https://github.com/fable-compiler/Fable/assets/884885/db74124d-ba17-46fa-a18f-0812fee10ff6)

Maybe related, there are a few fixes coming in F# 8.0.400 regarding `static abstract` https://github.com/dotnet/fsharp/blob/main/docs/release-notes/.FSharp.Compiler.Service/8.0.400.md

**Comment by ncave** [comment] 2024-06-19 19:14
@goswinr Static interface members (without implementation) are not supported (yet).
But static interface members with implementation are already supported.

 See #3829

**Comment by ncave** [comment] 2024-06-19 19:15
Closed as duplicate of #3829

**Closed by ncave** 2024-06-19 19:15 UTC
