### ISSUE TITLE
(dev2.0) Constructor mapping issue

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1453] opened 2018-06-28 22:15 UTC
If the .fsi constructor list does not match exactly the .fs implementation, the wrong constructor call is generated at call site.
- when the number of constructors is different.
- when the order of constructors is different.

Unfortunately since it's a code generation error, it will only manifest at runtime when it blows up.

**Comment by alfonsogarciacaro** [comment] 2018-06-29 11:12
This is striking again. I guess that it'll be a problem not only for constructors but also for other overloaded methods. We need to be sure we're checking the ImplementationEntity instead of the symbol coming from the signature file.

Would it be possible to have some code to reproduce this?

**Comment by alfonsogarciacaro** [comment] 2018-06-30 22:39
I cannot reproduce this :/ I'm trying with the following:

```fsharp
// Domain.fsi
namespace Domain

type MyType =
  new: unit -> MyType
  member Value: int

// Domain.fs
namespace Domain

type MyType(i: int) =
  new () = MyType(9)
  member __.Value = i

// This version works too

// type MyType =
//     new (v) = { value = v }
//     new () = { value = 9 }
//     val value : int
//     member x.Value = x.value

// QuickTest.fs

open Domain

let foo = MyType()
printfn "%i" foo.Value
```

Fable correctly calls `_Domain.MyType$$$$002Ector$$1`. That is, the second constructor with overload index `$$1`.

**Comment by ncave** [comment] 2018-06-30 22:44
@alfonsogarciacaro I wasn't able to reproduce it on small scale either (ot I would've posted it), but it's not holding the REPL back since I fixed FCS signatures to match implementation. Perhaps later I'll spend some time to reproduce it, but I'm trying to finish the REPL benchmark, really close now and looking good.

**Comment by ncave** [comment] 2018-06-30 23:29
@alfonsogarciacaro See for example the [src/fsharp/symbols/Symbols.fsi](https://github.com/ncave/FSharp.Compiler.Service/commit/f74b943b78f42133c41d40da51074cd822b5577d#diff-1e408252337cbfd37d4938ceb706a7ac).

**Comment by alfonsogarciacaro** [comment] 2018-08-30 08:00
I think this is fixed now with the overload hashes. Please reopen if it's still a problem.

**Closed by alfonsogarciacaro** 2018-08-30 08:00 UTC
