### ISSUE TITLE
Unable to execute function in generated JS in browser from inline JS.

### ISSUE THREAD

**Issue by dcook-net** [fable-compiler/Fable#3768] opened 2024-02-24 14:32 UTC
### Description

I'm attempting to simulate a scenario whereby I produce js with some validation rules and make that available to someone else, and they will reference that file and execute a 'validate' function. I might host this file on a CDN for example.

However, 
In the HTML when I reference the generated JS, I can't seem to call the validate function.
I can see it in the source that's pulled into the page, but get an error when attempting to invoke the function:

`"Uncaught runtime errors: × ERROR validate is not defined ReferenceError: validate is not defined at validateForm"`

I'm not really a js Dev, so I suspect I'm missing something!

### Repo code
https://github.com/dcook-net/FableExample/blob/main/README.md

### Expected and actual results
I expected the validate function to exec, and I'd be able to use the response to update the Dom with some error messages if there were any.

### Related information

* Fable version: 4.13.0
* Operating system: mac OS

**Comment by MangelMaxime** [comment] 2024-02-24 15:44
Hello,

This is normal that you can't access the `validate` function.

The function is only available from inside the `Program.fs.js` or your `bundle.js` in your case. You need to look on Webpack documentation how to expose a bundle as a library.

I think you want to look for the [`output.library.type`](https://webpack.js.org/configuration/output/#outputlibrarytype) options in webpack.

Depending on the option you should be able to use it via a variable, a globally available API or using import statement.

If you are new to JavaScript, you should also look at ESM modules as this is the type of JavaScript that Fable produce.

**Comment by dcook-net** [comment] 2024-02-25 13:59
Ok, thanks.
I've tried this and I can't get it to work.
Are there examples of this?

**Comment by dcook-net** [comment] 2024-02-27 20:35
Confirmed, I have this working:

webpack.config.js:
```
var path = require("path");

module.exports = {
    mode: "development",
    entry: "./src/Program.fs.js",
    optimization: {
        minimize: false
    },
    output: {
        path: path.resolve(__dirname, './src/public'),
        filename: 'Program.fs.js',
        libraryTarget: 'var',
        library: 'Program'
    },

    devServer: {
        static: "./public",
        port: 8080,
    }
}
```

package.json:
```
{
  "private": true,
  "scripts": {
    "postinstall": "dotnet tool restore",
    "start": "fable watch src --run webpack serve"
  },
  "dependencies": {
    "webpack": "^5.75.0",
    "webpack-cli": "^5.0.0",
    "webpack-dev-server": "^4.11.1"
  }
}
```

I'll update my repo shortly too.

**Comment by MangelMaxime** [comment] 2024-02-27 20:59
Thanks for confirming.

I am closing this issue, because the problem is not with Fable but the weback configuration.

**Closed by MangelMaxime** 2024-02-27 20:59 UTC
