### ISSUE TITLE
Code is unexpectedly executed multiple times

### ISSUE THREAD

**Issue by chadunit** [fable-compiler/Fable#1330] opened 2018-01-18 02:35 UTC
### Description

The code before a returned function executes every time the returned function is used.

### Repro code

[REPL link](http://fable.io/repl/#?code=let%20testPredicate()%20%3D%0D%0A%0D%0A%20%20let%20mutable%20callCount%20%3D%200%0D%0A%0D%0A%20%20%2F%2F%20Returns%20a%20function%20that%20tests%20a%20number%20for%20divibility%20by%20a%20provided%20number.%0D%0A%20%20let%20createDivisibleByPredicate%20divisibleBy%20%3D%0D%0A%20%20%20%20%2F%2F%20Do%20some%20potentially%20expensive%20initialization%20or%20side%20effects%20here...%0D%0A%20%20%20%20callCount%20%3C-%20callCount%20%2B%201%0D%0A%20%20%20%20printfn%20%22call%20count%20%3D%20%25i%22%20callCount%0D%0A%20%20%20%20%2F%2F%20Return%20the%20function.%0D%0A%20%20%20%20fun%20x%20-%3E%20x%20%25%20divisibleBy%20%3D%200%0D%0A%0D%0A%20%20%2F%2F%20Apply%20all%20predicate%20functions%20in%20a%20list%20and%20return%20true%20if%20all%20satisfied.%0D%0A%20%20let%20satisfyAllPredicates%20predicateList%20num%20%3D%0D%0A%20%20%20%20predicateList%0D%0A%20%20%20%20%7C%3E%20List.map%20(fun%20pred%20-%3E%20pred%20num)%0D%0A%20%20%20%20%7C%3E%20List.reduce%20(%26%26)%0D%0A%0D%0A%20%20%2F%2F%20Create%20a%20list%20of%20two%20predicate%20functions.%0D%0A%20%20let%20predicates%20%3D%20%5B%202%3B%203%20%5D%20%7C%3E%20List.map%20createDivisibleByPredicate%0D%0A%0D%0A%20%20%2F%2F%20Test%20the%20predicate%20list%20on%2020%20numbers.%0D%0A%20%20let%20filteredList%20%3D%20%5B%201%20..%2020%20%5D%20%7C%3E%20List.filter%20(satisfyAllPredicates%20predicates)%0D%0A%20%20printfn%20%22%25A%22%20filteredList%0D%0A%0D%0AtestPredicate()&html=%3Chtml%3E%3Cbody%3E%3C%2Fbody%3E%3C%2Fhtml%3E)

```
let testPredicate() =

  let mutable callCount = 0

  // Returns a function that tests a number for divibility by a provided number.
  let createDivisibleByPredicate divisibleBy =
    // Do some potentially expensive initialization or side effects here...
    callCount <- callCount + 1
    printfn "call count = %i" callCount
    // Return the function.
    fun x -> x % divisibleBy = 0

  // Apply all predicate functions in a list and return true if all satisfied.
  let satisfyAllPredicates predicateList num =
    predicateList
    |> List.map (fun pred -> pred num)
    |> List.reduce (&&)

  // Create a list of two predicate functions.
  let predicates = [ 2; 3 ] |> List.map createDivisibleByPredicate

  // Test the predicate list on 20 numbers.
  let filteredList = [ 1 .. 20 ] |> List.filter (satisfyAllPredicates predicates)
  printfn "%A" filteredList

testPredicate()
```

### Expected and actual results

I expected the initial lines of code in `createDivisibleByPredicate`, that are not part of the returned lambda function, to be executed twice due to being called in a List.map over two elements.

However, it appears that repeatedly calling the returned functions causes the those initial lines to be re-executed every time. In the browser console log, the printfn executes 40 times during the creation of `filteredList`.

For comparison, the same code executed in a .NET Core console app runs the printfn twice.

### Related information

* Fable version (`dotnet fable --version`): 1.3.7
* Operating system: Windows 10

**Comment by chadunit** [comment] 2018-01-18 07:23
Moving the create function to the top level instead of a nested function changes it to execute the initial printfn only twice as expected.

[Updated REPL](http://fable.io/repl/#?code=let%20mutable%20callCount%20%3D%200%0D%0A%0D%0A%2F%2F%20Returns%20a%20function%20that%20tests%20a%20number%20for%20divibility%20by%20a%20provided%20number.%0D%0Alet%20createDivisibleByPredicate%20divisibleBy%20%3D%0D%0A%20%20%2F%2F%20Do%20some%20potentially%20expensive%20initialization%20or%20side%20effects%20here...%0D%0A%20%20callCount%20%3C-%20callCount%20%2B%201%0D%0A%20%20printfn%20%22call%20count%20%3D%20%25i%22%20callCount%0D%0A%20%20%2F%2F%20Return%20the%20function.%0D%0A%20%20fun%20x%20-%3E%20x%20%25%20divisibleBy%20%3D%200%0D%0A%0D%0Alet%20testPredicate()%20%3D%0D%0A%0D%0A%20%20%2F%2F%20Apply%20all%20predicate%20functions%20in%20a%20list%20and%20return%20true%20if%20all%20satisfied.%0D%0A%20%20let%20satisfyAllPredicates%20predicateList%20num%20%3D%0D%0A%20%20%20%20predicateList%0D%0A%20%20%20%20%7C%3E%20List.map%20(fun%20pred%20-%3E%20pred%20num)%0D%0A%20%20%20%20%7C%3E%20List.reduce%20(%26%26)%0D%0A%0D%0A%20%20%2F%2F%20Create%20a%20list%20of%20two%20predicate%20functions.%0D%0A%20%20let%20predicates%20%3D%20%5B%202%3B%203%20%5D%20%7C%3E%20List.map%20createDivisibleByPredicate%0D%0A%0D%0A%20%20%2F%2F%20Test%20the%20predicate%20list%20on%2020%20numbers.%0D%0A%20%20let%20filteredList%20%3D%20%5B%201%20..%2020%20%5D%20%7C%3E%20List.filter%20(satisfyAllPredicates%20predicates)%0D%0A%20%20printfn%20%22%25A%22%20filteredList%0D%0A%0D%0AtestPredicate()&html=%3Chtml%3E%3Cbody%3E%3C%2Fbody%3E%3C%2Fhtml%3E)

```
let mutable callCount = 0

// Returns a function that tests a number for divibility by a provided number.
let createDivisibleByPredicate divisibleBy =
  // Do some potentially expensive initialization or side effects here...
  callCount <- callCount + 1
  printfn "call count = %i" callCount
  // Return the function.
  fun x -> x % divisibleBy = 0

let testPredicate() =

  // Apply all predicate functions in a list and return true if all satisfied.
  let satisfyAllPredicates predicateList num =
    predicateList
    |> List.map (fun pred -> pred num)
    |> List.reduce (&&)

  // Create a list of two predicate functions.
  let predicates = [ 2; 3 ] |> List.map createDivisibleByPredicate

  // Test the predicate list on 20 numbers.
  let filteredList = [ 1 .. 20 ] |> List.filter (satisfyAllPredicates predicates)
  printfn "%A" filteredList

testPredicate()
```

**Comment by alfonsogarciacaro** [comment] 2018-01-18 23:02
Thanks a lot for the detailed report and the code to reproduce the problem (as well as the variant) @chadunit. This seems to be caused by the wrapping Fable does to partially applied functions, I'll try to find a fix :+1:

**Comment by alfonsogarciacaro** [comment] 2018-01-22 23:04
[I tried to fix this](https://github.com/fable-compiler/Fable/commit/66d8122d14c7627d8fa94a5deaeda9f0e59141ce) but unfortunately it's causing other tests to fail. I'm currently working on a refactoring for Fable 2.0 that cleans up some of the current mess for function composition. Let's keep the issue open and see if it's easier to fix for the next major version :+1:

**Comment by alfonsogarciacaro** [comment] 2018-11-27 10:43
This should be fixed in Fable 2 :)

**Closed by alfonsogarciacaro** 2018-11-27 10:43 UTC
