### ISSUE TITLE
Function match parameters create unnecessary closures

### ISSUE THREAD

**Issue by Dessix** [fable-compiler/Fable#643] opened 2017-01-10 22:30 UTC
### Description

When a match is performed on a function value, the value is created via closure where passing a parameter would be preferred.

### Repro code

```FSharp
type TypeWithProperty() =
    member __.prop = Some [ 5.0; 2.0 ]
    member inline __.inlineProp = Some [ 42.0; 13.0 ]

[<EntryPoint>]
let main args =

    let locVal = Some [ 4.0; 2.0 ]
    //local non-function value; works nicely
    let x = match locVal with | Some x -> Some x.Head | _ -> None

    let locfunc() = Some [ 3.0; 4.0 ]
    //local function; exhibits issue
    let y = match locfunc() with | Some x -> Some x.Head | _ -> None

    let typeWithProperty = TypeWithProperty()
    //nonlocal value; exhibits issue
    let z = match typeWithProperty.prop with | Some x -> Some x.Head | _ -> None

    //nonlocal inline value; exhibits issue, inlining the match into an IIFE instead of reproducing the expected locVal case
    let q = match typeWithProperty.inlineProp with | Some x -> Some x.Head | _ -> None
```

### Expected and actual results

Compiled output:
```javascript
class TypeWithProperty {
  [FSymbol.reflection]() {
    return {
      type: "Main.TypeWithProperty",
      properties: {
        inlineProp: Option(makeGeneric(List$1, {
          T: "number"
        })),
        prop: Option(makeGeneric(List$1, {
          T: "number"
        }))
      }
    };
  }

  constructor() {}

  get prop() {
    return ofArray([5, 2]);
  }

}
setType("Main.TypeWithProperty", TypeWithProperty);

(function (args) {
  const locVal = ofArray([4, 2]);
  const x = locVal != null ? locVal.head : null;

  const locfunc = () => ofArray([3, 4]);

  const y = (() => {
    const matchValue = locfunc(null);

    if (matchValue != null) {
      return matchValue.head;
    }
  })();

  const typeWithProperty = new TypeWithProperty(null);

  const z = (() => {
    const matchValue = typeWithProperty.prop;

    if (matchValue != null) {
      return matchValue.head;
    }
  })();

  const q = (() => {
    const matchValue = ofArray([42, 13]);

    if (matchValue != null) {
      return matchValue.head;
    }
  })();

  return 0;
})(process.argv.slice(2));

exports.TypeWithProperty = TypeWithProperty;
```

Expected result:

In the latter 3 cases, the function to produce the value should be passed as a parameter to the IIFE, rather than embedded within it. Optimistically, in the inline case, the result should result in similar code to the locVal case.

Example:
```javascript
const z = (() => {
  const matchValue = typeWithProperty.prop;
  if (matchValue != null) {
    return matchValue.head;
  }
})();

//should be:

//Is there a need to conserve lexical "this" by using "=>"? A second performance bump arises if not
const z = (function(matchValue) {
  if (matchValue != null) {
    return matchValue.head;
  }
})(typeWithProperty.prop);//Note that it's passed into the function as a parameter. "matchValue.prop" could be performed internally if that's easier.
```

### Related information 

* fable-compiler version: 0.7.28
* fable-core version: 0.7.20
* Operating system: Win64

**Comment by alfonsogarciacaro** [comment] 2017-01-11 09:36
One of Fable main goals is to produce as readable and standard JS as possible, but that's not always easy because in F# everything is an expression while JS has expression and statements which there are things you cannot put in the place of an expression (like a scoped variable declaration as in this case).

Fable generates closures (`iife`s) to turn a sequence of statements that cannot be resolved into an expression. I try to avoid this whenever possible and recently I added some changes to remove closures (e.g. in conditional expressions). Actually I also checked the same case as in your example but my goal was to remove the inner function completely with something like:

```fsharp
let z = null;
const matchValue = typeWithProperty.prop;
if (matchValue != null) {
  z = matchValue.head;
}
```

Passing `matchValue` as argument could make the JS code slightly more readable but I'm not sure it'll improve performance that much as it doesn't remove the additional call in the stack (and, if I'm not wrong, the way closures work is the captured values are passed as hidden arguments, so the final result for the JS VM shouldn't be very different).

The problem I had when trying to remove the closure is that I had several tests failing and, as this is not a priority at the moment (I still need to update the docs), I didn't dedicate that much time to investigate the issue. You're very welcome to improve this part and send a PR though. If you're interested, I can search for my attempt to eliminate the closure in variable declarations (I think I have it in a local branch) and post it so you can have a look and continue from there if you want.

**Comment by Dessix** [comment] 2017-01-11 09:51
A closure is generated as a hidden class when a variable is pulled from the surroundings- Every time the scope of those surroundings is a "new" scope, the closure is recreated the next time that function's declaration expression is passed in evaluation. Essentially, converting it to an argument makes it a call, while a closure is a new scope being created, so a full-on object allocation.

The "fat arrow" syntax (() =>{}) is closer to having a new variable created for `this` and passed as the this-binding for the inner function, and is more performant than a closure (... though it can also *be* a closure, making it twice as fun), but the gist of it is that if you close over external variables, you're creating an allocation every time that line is called, but if you just pass them as arguments, you're only `call`-ing, which is much more performance-friendly.

**Comment by alfonsogarciacaro** [comment] 2017-01-11 17:40
Thanks a lot for the info! Yes, there are still many opportunities for optimizations but due to my limited capacity I cannot catch them all. As commented, any help is appreciated 😄 

The use of arrow functions is intended because the expected behavior in F# is the `this` context is captured in lambdas. TBH, how Fable handles `this` doesn't correspond to a very well designed plan as I had to deal with different situations as I found them. For example, in F# you can create and object expression within and object expression within a class and and the compiler must capture all the different `this`es (see [this test](https://github.com/fable-compiler/Fable/blob/75d8b97b653f5b15d358ace9db41be3088bca3de/src/tests/Main/MiscTests.fs#L279)). Also recently I modified the code to allow the use of JS `this` (`Fable.Core.JsInterop.jsThis`) as required by some JS libs, but [it must still be possible to use the enclosing `this`](https://github.com/fable-compiler/Fable/blob/75d8b97b653f5b15d358ace9db41be3088bca3de/src/fable/Fable.Compiler/FSharp2Fable.Util.fs#L1405-L1414) so... it gets complicated :wink:

**Comment by Dessix** [comment] 2017-01-12 01:10
I'm thinking the correct way to handle this bit would be to convert the parental "this" contexts to additional parameters on the inner contexts. It might need a bit of a change to the overall structure, in that it'll produce a less-direct mapping to JS, but will be a bit more accurate in terms of behaviour and how it's normally handled on the JS side.

I'll look into fixing it, but this sort of code is still very new to me. There's a few other bugs I have to report before I can get onto that, so I'm going to say this is low priority compared to issues of actual F# functionality being unavailable.

**Comment by alfonsogarciacaro** [comment] 2017-01-12 08:37
Not sure if that would work in all cases, because many times you're sending the lambda to external JS code, so you have no control on when it'll be called and with how many parameters. I'm already using the additional parameter trick for functions with the `PassGenerics` attribute but that's in the hope that only F# functions will need the generic info.

In any case, I definitely agree that F# functionality and actual bugs have priority over this kind of optimizations. Also, after updating the docs for users I'd like to clean up the code and add more internal documentation to make it easier for contributors :+1:

**Closed** 2017-05-11 21:25 UTC
