### ISSUE TITLE
Internal/private module definitions

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#696] opened 2017-02-02 08:20 UTC
Internal/private module definitions are not exporting functions. I understand that's by design, but it's not working as expected.

Example: [AstPass.tryReplace](https://github.com/ncave/Fable/blob/master/src/fable/Fable.Compiler/Replacements.fs#L1932) does not exist if AstPass is private module.

Work-around: Not using internal/private modules.

**Comment by alfonsogarciacaro** [comment] 2017-02-02 10:14
Hmm, I need to check this. I faced the same problem with internal types (they can used from another file in the same "assembly") so they're considered public. Private methods/modules shouldn't be exported as they're only used within the same module/file, however apparently F# AST considers public methods in a private module as public (maybe a bug), I need to see if this can be corrected: [reference](https://github.com/fable-compiler/Fable/blob/6e8475b81b28fd8c8d99a3959de0f4c223f62231/src/fable/Fable.Compiler/FSharp2Fable.Util.fs#L700)

**Comment by alfonsogarciacaro** [comment] 2017-02-02 16:08
This seems to be a problem of FCS (see the issue I just opened). Ideally this should be fixed there and we shouldn't need to expose private members in Fable. For now, as I guess this problem is affecting the JS compilation of Fable we can just remove the `private` modifier of the `AstPass` module.

**Comment by ncave** [comment] 2017-02-02 18:21
@alfonsogarciacaro Already removed in narumi.

**Closed** 2017-02-06 22:31 UTC

**Comment by alfonsogarciacaro** [comment] 2017-02-06 23:50
Fixed temporarily by just making all members of a private module public

**Comment by stkb** [comment] 2020-05-29 10:55
Is making all private modules internal still the only way to fix this? Came across this after trying to upgrade an old Fable v1 project

**Comment by MangelMaxime** [comment] 2020-05-29 13:37
Hello,

I don't know but from what I see in this issue it should have been fixed inside Fable compiler.

Could you please open a new issue with reproduction code and linking to this issue if the problem is similar?
