### ISSUE TITLE
F# 5.0 

### ISSUE THREAD

**Issue by TheAngryByrd** [fable-compiler/Fable#2054] opened 2020-05-12 21:11 UTC
### Description

Hey there! Now that[F# 5.0](https://devblogs.microsoft.com/dotnet/announcing-f-5-preview-1/) was announced, I'd just like to get conversation started about supporting (or not) all the new features listed. Specifically looking forward to support for applicatives.

**Comment by ncave** [comment] 2020-05-12 21:26
- It's a preview announcement, if I'm not wrong.
- Nonetheless, the 5.0 preview features should already be available (but untested) in the latest Fable releases (since 2.6.0). You'll have to enable the preview in your project file, of course:`<LangVersion>preview</LangVersion>`

Closing as duplicate of #2049, please feel free to reopen if you have to (or open specific issues if you encounter any).

**Closed by ncave** 2020-05-12 21:26 UTC

**Comment by TheAngryByrd** [comment] 2020-05-12 22:11
Thanks! FYI I'm extensively testing the `and!` applicative stuff over here in [FsToolkit.ErrorHandling](https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/75).
